### ISSUE TITLE
K8SSAND-487 ⁃ cass-operator image tag is not updated to v1.7.1 in cass-operator-manifests.yaml in 1.7.1 release

### ISSUE THREAD

**Issue by anoopps79** [k8ssandra/cass-operator#106]
**What happened?**

**Did you expect to see something different?**

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Cass Operator version:

    `Insert image tag or Git SHA here`
    
    * Kubernetes version information:    `kubectl version`
    * Kubernetes cluster kind:```insert how you created your cluster: kops, bootkube, etc.```* Manifests:```

insert manifests relevant to the issue

```

* Cass Operator Logs:

```

insert Cass Operator logs relevant to the issue here
```

**Anything else we need to know?**:



┆Issue is synchronized with this [Jira Bug](https://k8ssandra.atlassian.net/browse/K8SSAND-487) by [Unito](https://www.unito.io)
┆fixVersions: k8ssandra-1.2.0,cass-operator-1.7.1
┆friendlyId: K8SSAND-487
┆priority: Medium

**Comment by jsanda** [comment]
Hi @anoopps79 

Where are you getting cass-operator-manifests.yaml?

**Comment by anoopps79** [comment]
I checked 
the one in zip (https://github.com/k8ssandra/cass-operator/archive/refs/tags/v1.7.1.zip) 
as well as in this location (https://raw.githubusercontent.com/k8ssandra/cass-operator/v1.7.1/docs/user/cass-operator-manifests.yaml)

Both still have 
image: k8ssandra/cass-operator:v1.7.0

**Comment by anoopps79** [comment]
https://hub.docker.com/layers/k8ssandra/cass-operator/v1.7.1/images/sha256-252b5d3874d82808a86b90148b7926efd86b69726642f16e672c3fe67356f343?context=explore

Docker hub has the v1.7.1 tag listed

**Comment by anoopps79** [comment]
So may be we need to refresh the bits after the fix

**Comment by anoopps79** [comment]
Verified that it is fixed
