### ISSUE TITLE
K8SSAND-555 ⁃ Not compatible with Istio service mesh

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/cass-operator#114]
Issue originally reported in `datastax/cass-operator` #422 by springstim

**What is missing?**

There are several things that could be done to make the Cass operator compatible with Istio service mesh; currently I think this Cassandra operator is not usable on Istil 1.8 and above. Here are some suggestions to increase compatibility:

Remove the management API from the general services. I could be wrong but I don't think there is value in putting the management API port (i.e. 8080) into the general services. As soon as port 8080 appears in a service that has matching selectors for the pods, Istio no longer allows access to the datacenter pod's cluster IP.

Instead of adding the management API port 8080 to the general statefulSet services, create services for each datacenter StatefulSet member using the "statefulset.kubernetes.io/pod-name" selector; this way the DC pods can be referenced by a pod-specific service name

Do not have the operator attempt to connect to the DC pods via their clusterIPs as this is blocked by Istio sidecar proxies with mutual TLS enforced; instead use the pod-specific service names from "2." above. This allows Istio's mutual TLS capability to be used; when using pod/clusterIPs, Istio needs to be in a PERMISSIVE state or the Datacenter pods cannot start.

┆Issue is synchronized with this [Jira Bug](https://k8ssandra.atlassian.net/browse/K8SSAND-555) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-555
┆priority: Medium

**Comment by bradfordcp** [comment]
It's frustrating that we would need a service per pod. Do you have any links to docs on this matter?

**Comment by burmanm** [comment]
Closing stale tickets (reopen if this ever becomes interesting again).
