### ISSUE TITLE
K8SSAND-556 ⁃ Spring data cassandra - connection polling

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/cass-operator#115]
Issue originally submitted in `datastax/cass-operator` #419 by pralow

Creating connection from the spring web application to the Cassandra Cluster(Cass operator) is trying to use the private IP of the pod (nodetool status ip). which would not be exposed outside.

How to use Spring data connection polling without exposing the pod to the outside world ?

Thanks

┆Issue is synchronized with this [Jira Bug](https://k8ssandra.atlassian.net/browse/K8SSAND-556) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-556
┆priority: Medium

**Comment by bradfordcp** [comment]
This is accomplished either by having routing information for the private pod network available to the network where the spring application is deployed, utilizing an ingress, or host networking.
