### ISSUE TITLE
K8SSAND-557 ⁃ Cass-operator the password of the reaper is visible in the event log when request fails

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/cass-operator#116]
This issue was originally reported in datastax/cass-operator #414 by arianvp

**What happened?**

The issue is that the management API takes the password as a query-parameter; and if the request fails that causes the password to show up in the event log

**Did you expect to see something different?**

Passwords should not be leaked to logging.

┆Issue is synchronized with this [Jira Bug](https://k8ssandra.atlassian.net/browse/K8SSAND-557) by [Unito](https://www.unito.io)
┆affectedVersions: cass-operator-1.7.1
┆friendlyId: K8SSAND-557
┆priority: Medium

**Comment by burmanm** [comment]
Reaper integration is no longer in cass-operator.
