### ISSUE TITLE
K8SSAND-594 ⁃ Use cluster's default storage class if not specified explicitly

### ISSUE THREAD

**Issue by bsideup** [k8ssandra/cass-operator#123]
**What is missing?**

`storageClassName` is mandatory, while it could fallback to the current default class (annotated with `storageclass.beta.kubernetes.io/is-default-class: "true"`) for systems that are not performance critical

**Why do we need it?**

Many cloud providers create clusters with predefined StorageClasses that are fine for non-critical systems. Getting started with cass-operator would be much easier if they are used and remove one extra manual step from the "getting started" scenario.

**Environment**

Any k8s cluster.

* Cass Operator version:

Any (current is 1.7.1)

┆Issue is synchronized with this [Jira Bug](https://k8ssandra.atlassian.net/browse/K8SSAND-594) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-594
┆priority: Medium

**Comment by bradfordcp** [comment]
I'm open to this solution, but in my experience many of the cloud providers use `volumeBindingMode: Immediate` which will cause the cluster's pods to get stuck in a pending state should the volume end up provisioned in an AZ other than where the pod is located.

There isn't an easy way for us to check the mode is appropriate at this time. It may be possible with k8ssandra-operator. We need to check the default storage classes for our documented cloud providers to determine if this behavior should change.

**Comment by jsanda** [comment]
I think we can close this. I don't think it is something we want to do and definitely in k8ssandra. If there still is interest a new issue should be opened in k8ssandra-operator.

**Comment by burmanm** [comment]
Closing this, if still necessary - reopen discussion in k8ssandra-operator.
