### ISSUE TITLE
K8SSAND-645 ⁃ apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition

### ISSUE THREAD

**Issue by msmygit** [k8ssandra/cass-operator#126]
**What happened?**
W0628 07:31:17.111849    6266 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
**Did you expect to see something different?**
use apiextensions.k8s.io/v1 CustomResourceDefinition

**How to reproduce it (as minimally and precisely as possible)**:
Just follow the normal installation

**Environment**
NA

* Cass Operator version:
the latest
`Insert image tag or Git SHA here`

* Kubernetes version information:

    `kubectl version`
    * Kubernetes cluster kind:```
insert how you created your cluster: kops, bootkube, etc.
```

* Manifests:

```
insert manifests relevant to the issue
```

* Cass Operator Logs:

```
insert Cass Operator logs relevant to the issue here
```

**Anything else we need to know?**:



┆Issue is synchronized with this [Jira Bug](https://k8ssandra.atlassian.net/browse/K8SSAND-645) by [Unito](https://www.unito.io)
┆epic: Deployments on k8s v1.22 fail
┆fixVersions: k8ssandra-1.4.0
┆friendlyId: K8SSAND-645
┆priority: Medium

**Comment by jdonenine** [comment]
@burmanm this would get covered with the current SDK/API upgrade work going on, right?

**Comment by burmanm** [comment]
Yep

**Comment by burmanm** [comment]
Fixed in master.
