### ISSUE TITLE
K8SSAND-683 ⁃ PSP features are not enabled in the master

### ISSUE THREAD

**Issue by burmanm** [k8ssandra/cass-operator#131]
**What happened?**
The master has no VMware specific PSP (PersistentServicesPlatform) features enabled. The features are still in the code, but the controller does not listen for those events and the tests for them are disabled.

**Anything else we need to know?**:
We currently have no infra for running VMware specific version of Kubernetes to test/dev these features.

┆Issue is synchronized with this [Jira Bug](https://k8ssandra.atlassian.net/browse/K8SSAND-683) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-683
┆priority: Medium

**Comment by bradfordcp** [comment]
At this point what should we do with this logic? It's not enabled and we don't have a way to test it. Push it to a branch and cleanup main? @jsanda @burmanm

**Comment by jsanda** [comment]
works for me
