### ISSUE TITLE
K8SSAND-684 ⁃ User documentation is out of date for 1.8.0

### ISSUE THREAD

**Issue by burmanm** [k8ssandra/cass-operator#132]
**What is missing?**
The process of installing has changed in 1.8.0. Also, the update from 1.7.0 -> 1.8.0 is not just an update for the image itself as it needs some additional changes to the deployment and CRD handling.

**Why do we need it?**
The old helm charts have been removed and will no longer function. The updated method is to use Kustomize (kubectl -k)

* Cass Operator version:
1.8.0

┆Issue is synchronized with this [Jira Bug](https://k8ssandra.atlassian.net/browse/K8SSAND-684) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-684
┆priority: Medium

**Comment by jsanda** [comment]
>The updated method is to use Kustomize (kubectl -k)

For what its worth in the past I have run into problems with `kubectl -k` due to kubectl using an older version of kustomize. I pretty much always use the `kustomize` binary now.

**Comment by burmanm** [comment]
That is true. However, I want to test that the kubectl -k works.
