### ISSUE TITLE
Support omitting uid and gid from SecurityContext

### ISSUE THREAD

**Issue by bradfordcp** [k8ssandra/cass-operator#14]
On OpenShift when using C* we use an empty SecurityContext and it behaves as expected. When running DataStax Enterprise we set this to 999 which is forbidden on OpenShift.

**Comment by jsanda** [comment]
Overriding the SecurityContext via the `PodTemplateSpec` property won't work currently. [buildPodTemplateSpec](https://github.com/k8ssandra/cass-operator/blob/v1.6.0/operator/pkg/reconciliation/construct_podtemplatespec.go#L498) The SecurityContext is set after that function is called which will overwrite anything added via the `PodTemplate` property.
