### ISSUE TITLE
K8SSAND-730 ⁃ Investigate if separate system-logger-image can be dropped after min. Kube 1.17 support

### ISSUE THREAD

**Issue by burmanm** [k8ssandra/cass-operator#147]
**Why do we need it?**
We currently build system-logger-image for sidecar usage to ensure we have fast shutdowns of the node. This is the PID signal handling is not killing tail when shutting down the pod and it hangs waiting for the soft 30s shutdown.

This might be solvable through ``shareProcessNamespace: true`` since it changes how both pods have their PID and signals handled. This is only available in Kube 1.17 and newer.

https://kubernetes.io/docs/tasks/configure-pod-container/share-process-namespace/

┆Issue is synchronized with this [Jira Bug](https://k8ssandra.atlassian.net/browse/K8SSAND-730) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-730
┆priority: Medium

**Comment by bradfordcp** [comment]
I believe we moved our minimum version to something higher than 1.17. Can we move forward with investigating if this will work?

**Comment by bradfordcp** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/K8ssandra-Grooming-623b197f1fcd4800110540ef/issues/k8ssandra/cass-operator/147?planning-poker) with ZenHub @burmanm

**Comment by burmanm** [comment]
We could indeed investigate this now, it would simplify operations in the certified repositories.

**Comment by bradfordcp** [comment]
I'm curious if there are any special security changes like `privileged: true`.

**Comment by burmanm** [comment]
Lets investigate this as part of the #338 or other logging changes if we do such.
