### ISSUE TITLE
K8SSAND-737 ⁃ Sometimes observedGeneration never gets updated to `spec.metadata.generation`, making `kubectl wait --for` not work

### ISSUE THREAD

**Issue by arianvp** [k8ssandra/cass-operator#149]
**What happened?**

Sometimes `status.observedGeneration` never gets in sync with `spec.metadata.generation`.  When they're
not in sync, `kubectl wait --for=status=Ready` never succeeds as `kubectl wait` first check if the `observedGeneration` is in sync.  This makes `kubectl wait` fail even if the `CassandraDatacenter` is ready

**Did you expect to see something different?**

Every time `cass-operator` does a reconciliation loop it should update `observedGeneration` to the latest `spec` that it saw

**How to reproduce it (as minimally and precisely as possible)**:

Not sure. It sometimes just doesn't happen.  E.g. I think I got into this situation when I set `spec.stopped: true` followed by `spec.stopped: false`. 

It seems like the comment here https://github.com/k8ssandra/cass-operatorhttps://github.com/k8ssandra/cass-operator/blob/15917792ae37b3b6a1e47aa3bd1891d35b375f08/pkg/reconciliation/constructor.go#L55 alludes to this not being optimally implemented yet.

**Environment**

* Cass Operator version:

    `Insert image tag or Git SHA here`
    
    * Kubernetes version information:    `kubectl version`
    * Kubernetes cluster kind:```insert how you created your cluster: kops, bootkube, etc.```* Manifests:

```

insert manifests relevant to the issue

```

* Cass Operator Logs:

```

insert Cass Operator logs relevant to the issue here
```

**Anything else we need to know?**:

┆Issue is synchronized with this [Jira Bug](https://k8ssandra.atlassian.net/browse/K8SSAND-737) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-737
┆priority: Medium

**Comment by burmanm** [comment]
There's been some other work around generation / observedgeneration outside this ticket, so I'm closing this until it's reproducable. Reopen if more details are available.
