### ISSUE TITLE
K8SSAND-826 ⁃ Affinity labels defined at rack-level should have precedence over DC-level ones

### ISSUE THREAD

**Issue by adutra** [k8ssandra/cass-operator#162]
**What happened?**

When the same affinity label is defined both at DC level and at rack level, the DC-level value wins.

**Did you expect to see something different?**

I would expect the rack-level value to win.

**How to reproduce it (as minimally and precisely as possible)**:

I would expect the below test to pass, but it doesn't.

```java
func TestRackAffinityLabels(t *testing.T) {
	dc := &api.CassandraDatacenter{
		Spec: api.CassandraDatacenterSpec{
			ClusterName: "cluster1",
			NodeAffinityLabels: map[string]string{
				"label1": "dc",
				"label2": "dc",
			},
			Racks: []api.Rack{{
				Name: "rack1",
				NodeAffinityLabels: map[string]string{
					"label2": "rack",
					"label3": "rack",
				},
			}},
		},
	}
	actual, _ := rackNodeAffinitylabels(dc, "rack1")
	expected := map[string]string{
		"label1": "dc",   // only in dc
		"label2": "rack", // in dc and rack
		"label3": "rack", // only in rack
	}
	assert.Equal(t, expected, actual)
}
```

**Environment**

Not relevant.

**Anything else we need to know?**:

The issue seems to stem from this statement:

```java
nodeAffinityLabels = utils.MergeMap(
	emptyMapIfNil(rack.NodeAffinityLabels),
	emptyMapIfNil(dc.Spec.NodeAffinityLabels),
)
```

Given how `MergeMap` works, the second map entries will override the first map ones.
If you change it as below, the test passes.

```java
nodeAffinityLabels = utils.MergeMap(
	emptyMapIfNil(dc.Spec.NodeAffinityLabels),
	emptyMapIfNil(rack.NodeAffinityLabels),
)
```

┆Issue is synchronized with this [Jira Bug](https://k8ssandra.atlassian.net/browse/K8SSAND-826) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-826
┆priority: Medium

**Comment by burmanm** [comment]
Throw a PR, I agree with the assumption that rack-level wins.
