### ISSUE TITLE
K8SSAND-881 ⁃ Create kustomize overlay for installing cert-manager

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/cass-operator#168]
**What is missing?**
cert-manager is now a dependency of cass-operator. While cass-operator can now be installed via kustomize, you have to install cert-manager as separate, prerequisite step.

**Why do we need it?**
It will simplify the install process and also make it easier for other projects looking to include cass-operator via kustomize.

* Cass Operator version:
1.8.0-rc.1

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-881) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-881
┆priority: Medium

**Comment by adejanovski** [comment]
cert-manager needs to be installed with cluster scope, which wouldn't be possible if we set it as a dependency on namespace scoped k8ssandra/cass-operator installs.

Closing as won't do.
