### ISSUE TITLE
K8SSAND-884 ⁃ Not compatible with Kubernetes 1.22

### ISSUE THREAD

**Issue by owetterau** [k8ssandra/cass-operator#169]
When trying to install the cass operator on Kubernetes 1.22 like this

`kubectl apply -n cass-operator -f https://raw.githubusercontent.com/k8ssandra/cass-operator/v1.7.1/docs/user/cass-operator-manifests.yaml
`

it fails with the following error message:

```
unable to recognize "https://raw.githubusercontent.com/k8ssandra/cass-operator/v1.8.0-rc.1/docs/user/cass-operator-manifests.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
unable to recognize "https://raw.githubusercontent.com/k8ssandra/cass-operator/v1.8.0-rc.1/docs/user/cass-operator-manifests.yaml": no matches for kind "ValidatingWebhookConfiguration" in version "admissionregistration.k8s.io/v1beta1"
```

The reason for this is that `apiextensions.k8s.io/v1beta1` and `admissionregistration.k8s.io/v1beta1` are not supported anymore and have been replaced with the `*/v1` version.

┆Issue is synchronized with this [Jira Bug](https://k8ssandra.atlassian.net/browse/K8SSAND-884) by [Unito](https://www.unito.io)
┆fixVersions: cass-operator-1.8.0,k8ssandra-1.4.0
┆friendlyId: K8SSAND-884
┆priority: Medium

**Comment by burmanm** [comment]
1.7.1 is known to not work on Kubernetes 1.22. These versions were updated for the 1.8 release, but there's only a rc-1 available at this point. 

If you wish to try 1.8-rc.1, then installation using Kustomize is available. 

``
kubectl apply -k github.com/k8ssandra/cass-operator/config/default?ref=v1.8.0-rc.1
``

The config/default creates namespace "cass-operator" and installs there (use kustomize to modify that). It requires cert-manager if you have webhooks enabled.

**Comment by owetterau** [comment]
I already tested 1.8.0-rc1 and unfortunately it appears to have the same issue.

**Comment by jsanda** [comment]
I think it makes sense to get this fixed for 1.8.0.

**Comment by burmanm** [comment]
All CustomResourceDefinitions are v1 in 1.8.0. Same for ValidatingWebhookConfiguration. The deployment model is different, one can't deploy from 1.8.0 branch the old 1.7.1 docs (they will not deploy 1.8.0).

**Comment by burmanm** [comment]
In short, this error message:

```
unable to recognize "https://raw.githubusercontent.com/k8ssandra/cass-operator/v1.8.0-rc.1/docs/user/cass-operator-manifests.yaml": 
```

Indicates the 1.7.1 was installed from 1.8.0 branch. It's still only going to deploy 1.7.1 (the docs of 1.8.0 branch have not been updated).

**Comment by owetterau** [comment]
If that is the case, how can I install the 1.8 branch, if the docs are still in version 1.7.1?

Or does it only mean that the docs need to be updated?

**Comment by burmanm** [comment]
Try the: ``kubectl apply -k github.com/k8ssandra/cass-operator/config/default?ref=v1.8.0-rc.1`` command.

**Comment by owetterau** [comment]
Unfortunately, that command produces different errors:
```
unable to recognize "github.com/k8ssandra/cass-operator/config/default?ref=v1.8.0-rc.1": no matches for kind "Certificate" in version "cert-manager.io/v1"
unable to recognize "github.com/k8ssandra/cass-operator/config/default?ref=v1.8.0-rc.1": no matches for kind "Issuer" in version "cert-manager.io/v1"
```

**Comment by burmanm** [comment]
Yes, you need to install cert-manager if you went for default installation and don't have it.

``
kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.3.1/cert-manager.yaml
``

**Comment by owetterau** [comment]
Thanks a lot for the quick and good help! That did the trick...
