### ISSUE TITLE
K8SSAND-892 ⁃ #171 - Update e2e tests to cover Kubernetes 1.23

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/cass-operator#171]
cass-operartor 1.8.0-rc.1 already works with k8s 1.22 but that's not the version we are targeting for library dependencies and for e2e tests. For 1.8.0 I would like to see k8s dependencies updated to 1.22 and see tests in GHA run against 1.22.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-892) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-892
┆priority: Medium

**Comment by burmanm** [comment]
I think this should be postponed beyond 1.8.0. It's a very new Kube release and most of the development for 1.8.0 was done before it was released.

**Comment by jimdickinson** [comment]
+1 for defer. 1.22 isn't available on any cloud, yet, AFAICT. GKE Rapid channel is still 1.21, and we've traditionally targeted Regular / Stable for cass-operator.

**Comment by burmanm** [comment]
After some more testing, this does not work. Not on my Kind installation on MacOS (Docker for Desktop) or GHA. It's not that the software doesn't work, but tests run out of file watches, file descriptors or something else. Too many open files from Java processes in DSE tests always popup.
