### ISSUE TITLE
K8SSAND-917 ⁃ Add full query logging to reconciliation loop

### ISSUE THREAD

**Issue by Miles-Garnsey** [k8ssandra/cass-operator#175]
We have a number of PRs + issues open across 3 repos to add full query logging capabilities to k8ssandra, since it was added in Cassandra 4.0.0.

Management API - https://github.com/k8ssandra/management-api-for-apache-cassandra/issues/131
Cass config builder (definition submodule) - https://github.com/datastax/cass-config-definitions/pull/65
k8ssandra helm charts - https://github.com/k8ssandra/k8ssandra/issues/1102

I think we may also need to add a call to the management API  from cass-operator. This will ensure that the system state is brought into the target  state described in the `CassandraDatacenter` (and propagated to Cassandra via `cassandra.yaml`) during the reconciliation loop.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-917) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-917
┆priority: Medium

**Comment by jsanda** [comment]
Why would we need to call the management-api? If query logging is enabled that will trigger a statefulset update, i.e., a rolling restart which means the change will take effect.
