### ISSUE TITLE
K8SSAND-927 ⁃ Cassandra 4.0 example configurations

### ISSUE THREAD

**Issue by jeffreyscarpenter** [k8ssandra/cass-operator#181]
Add example configurations for deploying Cassandra 4.0 with cass-operator under https://github.com/k8ssandra/cass-operator/tree/master/operator/example-cassdc-yaml

Suggest this as a good first issue that someone could build, using the Cassandra 3.11 examples under that directory as a starting point.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-927) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-927
┆priority: Medium

**Comment by burmanm** [comment]
config/samples uses Cassandra 4.0.x already.
