### ISSUE TITLE
K8SSAND-937 ⁃ Expose CassandraDatacenter status as metrics

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/cass-operator#184]
What is missing?

Expose various status indicators from the CassandraDatacenter resources as metrics that could be scraped and aggregated by 3rd party tools.

Why do we need it?

So that 3rd party observability and alerting tools can monitor, visualize, and more easily create custom thresholds to establish the status of the cluster.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-937) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-937
┆priority: Medium

**Comment by adejanovski** [comment]
We'd need to agree on how to implement this but put the ticket in the Icebox as it is low priority.
