### ISSUE TITLE
K8SSAND-953 ⁃ Kube 1.22  / Openshift 4.9 deprecated APIs

### ISSUE THREAD

**Issue by prasanthcaibmcom** [k8ssandra/cass-operator#194]
This issue is filed on behalf of IBM Cloud Pak for Data engineering team.

In reviewing the CSV for the latest 1.7.1 of the cass operator:
https://github.com/k8ssandra/cass-operator/blob/ko-264-olm-integration/operator/bundle/1.7.1/manifests/cass-operator.v1.7.1.clusterserviceversion.yaml

We notice references to the v1beta API.  This, among others, is being deprecated/removed in Kube 1.22 and Openshift 4.9

Is there an awareness of compatibility against Kube 1.22?
OCP 4.9, which releases later this month (October 2021), will also be moving onto Kube 1.22.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-953) by [Unito](https://www.unito.io)
┆fixVersions: k8ssandra-1.4.0
┆friendlyId: K8SSAND-953
┆priority: Medium

**Comment by burmanm** [comment]
These were fixed in the latest release of cass-operator (1.8.0).

**Comment by prasanthcaibmcom** [comment]
@burmanm Thanks.  Where can we get the OLM bundle?  Our integration point between IBM -> Datastax is the OLM bundle, and we pick up from here:
https://github.com/k8ssandra/cass-operator/tree/ko-264-olm-integration/operator/bundle

**Comment by burmanm** [comment]
Ah, there's no final OLM bundle for new operator-sdk structure yet. We do create one during the release process, but it's not production quality yet:

https://hub.docker.com/layers/k8ssandra/cass-operator-bundle/v1.8.0/images/sha256-248b2467e0dcc89aab6ecdf24cb1d44afdd3720fc8bbab3be69fd6c8d9e592ff?context=explore

It's missing most of the modifications to the ClusterServiceVersion. This is on my TODO list.. I'll create a ticket to remind myself.
