### ISSUE TITLE
Create OLM bundle for 1.8.0

### ISSUE THREAD

**Issue by burmanm** [k8ssandra/cass-operator#195]
**What is missing?**
We currently create only a skeleton version of the OLM bundle & catalog files, but they do not include all the information that the previous versions have included and as such are not automatically deployable after we create a release. We should seek to include all the necessary information in them.

**Why do we need it?**
Openshift integration needs it for OperatorHub, as mentioned in  #194

**Comment by jdonenine** [comment]
Reopened as #207
