### ISSUE TITLE
Tests need to verify that everything works with older mgmt-api versions also

### ISSUE THREAD

**Issue by burmanm** [k8ssandra/cass-operator#201]
**What happened?**
As seen in PR #176 , if we had only tested this with a new version of management-apis, all the tests would pass. But as soon as user would use an older version things would break completely and the cass-operator is completely unusable. We need to verify that new features that use newer features from management-api also work with older serverImages.

**Comment by jsanda** [comment]
It's not clear to me that we need to do this. Don't get me wrong. It would certainly be good to do, but I question whether it is necessary. Alternatively would it be sufficient to simply document version compatibility?

@jdonenine What are your thoughts?
