### ISSUE TITLE
K8SSAND-986 ⁃ Cassandra datacenters use the default service account on Openshift

### ISSUE THREAD

**Issue by prasanthcaibmcom** [k8ssandra/cass-operator#208]
This is an requirement filed on behalf of IBM Cloud Pak team.

**What did you do?**
Deploy a CassandraDatacenter and observe resulting service accounts and security contexts being used.

We observed the `default` service account was being used.

This is discouraged by our internal certification.  Operators should create their own service accounts so that the privileges are managed.

Does the operator create a service account to be used by its operands, or conversely, is there a particular service account definition/privileges that we could create manually and use for our CassandraDatacenters?

**Environment**

Openshift 4.8

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-986) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-986
┆priority: Medium

**Comment by jdonenine** [comment]
Hi @prasanthcaibmcom, thanks for the question!  The default service account is only used when another is not provided to be used.  An alternative service account, that has the desired permissions associated with it, should be created external to the operator and provided to it to use.  Hopefully that will fit your needs.

You can provide the desired service account though this portion of the spec:  https://github.com/k8ssandra/cass-operator/blob/9b1d3797278a5cd1653d64611a312427d1b0a482/config/crd/bases/cassandra.datastax.com_cassandradatacenters.yaml#L5160
