### ISSUE TITLE
K8SSAND-162 ⁃ Replace usage of WaitForDatacenterReady functions in tests

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/cass-operator#21]
This ticket applies to all variant of `WaitForDatacenterReady` which include:

* `WaitForDatacenterReady`
* `WaitForDatacenterReadyWithTimeouts`
* `WaitForDatacenterReadyPodCountWithTimeout`

There might be others that I missed. Each variants calls into `WaitForDatacenterReadyPodCountWithTimeout`. This function polls until the `status.phase` of each pod is set to `Running`. This is problematic because this is not the same thing as the pod being ready.  It just means that at least one application container is running. Before realizing this I was burn a few times trying to track down intermittent failures.

In general we probably should be checking that the `Ready` condition has a status of `true`. This can be done as follows:

```go
ns.WaitForDatacenterCondition(dcName, string(api.DatacenterReady), string(corev1.ConditionTrue))
```

For this ticket we should do a full audit of all places where these `WaitForDatacenterReady` functions are used and update accordingly.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-162) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-162
┆priority: Medium

**Comment by burmanm** [comment]
Closing stale tickets (reopen if this ever becomes interesting again).
