### ISSUE TITLE
K8SSAND-998 ⁃ Provide MCAC's base configuration external from the image

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/cass-operator#212]
**What is missing?**
This is related to #199 and part of the effort to make the root file system read-only. MCAC's config files, which are located at  `/opt/metrics-collector/config` are part of the managment-api image. There are two config files:

* `collectd.conf.tmpl`
* `metric-collector.yaml`

These files get updated in the management-api entry point script which is problematic if we want to configure the root file system to be read only.

The solution I am proposing is basically the same as that in #211.

MCAC's base config files will be provided in a ConfigMap that becomes part of the cass-operator installation. If the base config's differ across Cassandra versions then there will need to be a ConfigMap for each supported Cassandra version/image. The operator will determine which ConfigMap to use based on the `ServerVersion` in the CassandraDatacenter spec.

cass-operator adds a ConfigMap volume which is mounted at something like `/mcac-base-config`. Let's call this volume `mcac-base-config`. This volume should be read-only. cass-operator creates another, EmptyDir volume for `/opt/metrics-collector`. Let's call this volume `mcac-config`. It will shadow the `/opt/metrics-collector/config` directory that is part of the image. That's ok. 

An init container with a volume mount for `/mcac-base-config` will copy the base configuration files onto the `mcac-config` volume which is mounted at `/opt/metrics-collector/config`. This init container should run before any other init containers. Note that in #211 I described a similar init container. I think that the same init container can handle copying the base configs for both Cassandra and MCAC.

The management-api entry point script can continue to write to /opt/metrics-collector/config as it does today.

**Environment**

* Cass Operator version:

v1.8.0

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-998) by [Unito](https://www.unito.io)
┆epic: Security Phase II
┆friendlyId: K8SSAND-998
┆priority: Medium

**Comment by burmanm** [comment]
Closing this as it is no longer relevant due to the new /metrics endpoint.
