### ISSUE TITLE
K8SSAND-163 ⁃ Share message in the appropriate channels (mailing lists, slack channels, etc.) to reflect migration completion

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/cass-operator#22]
┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-163) by [Unito](https://www.unito.io)
┆fixVersions: k8ssandra-1.2.0
┆friendlyId: K8SSAND-163
┆priority: Medium

**Comment by johnsmartco** [comment]
Jeff @jdonenine, I _think_ this was done. Do you agree?  If so, please close this issue.  It looks like I don't have permissions in this repo to Close 'em. Note that the docs reflect the change, e.g. such as:

- https://docs.datastax.com/en/cass-operator/doc/cass-operator/cassOperatorTOC.html

- https://docs.datastax.com/en/cass-operator/doc/cass-operator/cassOperatorReleaseNotes.html#cassOperatorReleaseNotes__cassOperatorReleaseNotes170changes
