### ISSUE TITLE
Update datastax.com documentation to reflect migration completion

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/cass-operator#23]

**Comment by johnsmartco** [comment]
Updated in topics such as:

- https://docs.datastax.com/en/cass-operator/doc/cass-operator/cassOperatorTOC.html
- https://docs.datastax.com/en/cass-operator/doc/cass-operator/cassOperatorReleaseNotes.html#cassOperatorReleaseNotes__cassOperatorReleaseNotes170changes

Michael @burmanm, please close this issue. Thanks!
