### ISSUE TITLE
K8SSAND-1052 ⁃ No options to add labels on the statefulset object

### ISSUE THREAD

**Issue by piclemx** [k8ssandra/cass-operator#235]
**What happened?**
I trying to add labels to the statefulset because of our policy in our cluster. Does it possible currently with the operator?

I saw that we have `podTemplateSpec` and I added those. But seems to add it only on the pod not the statefulset object?

**Did you expect to see something different?**
Add the possibility to add the labels on all resources created.

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Cass Operator version:

    `Insert image tag or Git SHA here`
    
    * Kubernetes version information:docker.io/k8ssandra/cass-operator:v1.7.1

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1052) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1052
┆priority: Medium

**Comment by burmanm** [comment]
There's currently no method to add user defined labels in the generated StatefulSet. podTemplateSpec only adds the details to the StatefulSet's podTemplateSpec which is why StatefulSet itself doesn't get added labels from there.

**Comment by piclemx** [comment]
@burmanm I can add it if you want. What will be the best way to do it?

**Comment by jsanda** [comment]
I was going to suggest a field like `AdditionalLabels` that would apply the labels not only to the StatefulSets but to all objects that the operator creates, but then I remembered we already have an `AdditionalServiceConfig` field for adding lables/annotations to services. Given that and if you only want to add labels to the StatefulSets then maybe something like `AdditionalStatefulSetConfig`.

**Comment by piclemx** [comment]
@jsanda I prefer the first option I think IMO. Operator should always give the possibility to the user to add some labels. Often is related to the enterprise policy for tagging stuff. 

I don't know what you think. Do you think we should used the `v1.Object.Metadata`? So if someone want to add not just labels but other metadata we will have the options.

**Comment by jsanda** [comment]
I would create/use a struct that has the fields from ObjectMetadata that you want which I assume is primarily labels and maybe annotations.

**Comment by burmanm** [comment]
Most likely the AdditionalLabels+AdditionalAnnotations type of struct would make more sense. That would be checked in the `labels.go`, `AddKubernetesLabels` and added there after the normal Kubernetes annotations. That would include those labels to every resource that cass-operator creates. It would also allow to override previous labels, such as `app.kubernetes.io/name` or `instance` if the user wanted.

**Comment by burmanm** [comment]
Adding only to the StatefulSet sounds odd since it's not "external" in a sense, like the services in some cases are.

**Comment by piclemx** [comment]
Yeah. I will try to open a PR today related to that.

**Comment by piclemx** [comment]
@burmanm  I'm talking about adding labels for everything that the operator creates. 

Do you think I should add the `AdditionalLabels` and `AdditionalAnnotations` in the spec `cassandradatacenter_types.go`?
