### ISSUE TITLE
K8SSAND-1120 ⁃ How to deliver Cassandra CDC (Pulsar Luna Streaming) Agent to C*/DSE cluster via Cass-Operator on a k8s cluster?

### ISSUE THREAD

**Issue by mparikhcloudbeds** [k8ssandra/cass-operator#249]
The CDC Pulsar/Luna Streaming Agent Install documentation is here : 
https://docs.datastax.com/en/cdc-for-cassandra/cdc-apache-cassandra/1.0.0/install.html

As it states, each C*/DSE node should have the Java Agent installed and requires a rolling restart. 

Kindly share the best approach and an example of achieving this on a k8s installation

Current Setup:

* Cass-Operator : 1.8
* DSE Version : 6.8.18
* Luna Streaming : 2.8

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1120) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1120
┆priority: Medium

**Comment by burmanm** [comment]
The best approach is to create a custom DSE image that has the java-agent in it. After that, modify the imageConfig of Cass-operator to force that custom image when DSE version is set to 6.8.18 (or set image manually in the CassandraDatacenter for each dc).

**Comment by mparikhcloudbeds** [comment]
thnx @burmanm !

Looking at 1.8.* spec, I think we would be using the below property and set it with our own docker image URL?

` serverImage: ""`

**Comment by burmanm** [comment]
Yes, that would be correct.

**Comment by jsanda** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/K8ssandra-Grooming-623b197f1fcd4800110540ef/issues/k8ssandra/cass-operator/249?planning-poker) with ZenHub @burmanm @Miles-Garnsey

**Comment by Miles-Garnsey** [comment]
This is being estimated under the other two tickets [here](https://k8ssandra.atlassian.net/browse/K8SSAND-1424) @jsanda.

I don't know if this ticket is still needed as it was basically a support/"how do I" ticket, whereas the new tickets are there to automate the steps described in this ticket.

**Comment by jsanda** [comment]
I was also unclear if this ticket is still needed. Sounds like we can close it.

**Comment by bradfordcp** [comment]
Closing given the other work going on around CDC in our containers. Cheers!
