### ISSUE TITLE
K8SSAND-1138 ⁃ additionalSeeds does not accept DNS

### ISSUE THREAD

**Issue by sahid** [k8ssandra/cass-operator#253]
When setting `additionalSeeds` It is from my understanding expected to use the DNS name of the service `xxx-seed-service` created by cass-operator but it looks like the API is expecting an IP address.

* Are there any requirements needed that I missed using that field?
* If not, I'm wondering whether it is expected behavior and the reason?

From the code POV we can see:

The API seems to expect a list of strings:

* https://github.com/k8ssandra/cass-operator/blob/0a85469787be456edf54ed5fc621a746acb6c0eb/apis/cassandra/v1beta1/cassandradatacenter_types.go#L201

A check on format happens here:

* https://github.com/k8ssandra/cass-operator/blob/0a85469787be456edf54ed5fc621a746acb6c0eb/pkg/reconciliation/construct_service.go#L159

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1138) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1138
┆priority: Medium

**Comment by burmanm** [comment]
Hi, the additionalSeeds is a list of DNS or IP addresses which one wants to use as the additional seeds in Cassandra. The service clusterName-additional-seeds is result of this setting - it's the DNS Name that Cassandra sees. cass-operator sets the additional-seed service to include the addresses you set in the CassandraDatacenter's additionalSeeds property. 

The integration test describes pretty well the intended behaviour:

https://github.com/k8ssandra/cass-operator/blob/master/tests/additional_seeds/additional_seeds_suite_test.go

**Comment by sahid** [comment]
That is what the operator is returning:
```
Endpoints "xxx-operator-additional-seed-service" is invalid: [subsets[0].addresses[0].ip: Invalid value: "xxx-seed-service.az1": must be a valid IP address, (e.g. 10.9.8.7 or 2001:db8::ffff), subsets[0].addresses[0].ip: Invalid value: "xxx-seed-service.az1": must be a valid IP address]
```

It seems that it tries to create an Enpoints.

To reproduce the issue, just create a dc and set the field `additionalSeeds`.

The usecase is that, I would like two dc to communicate together.

**Comment by burmanm** [comment]
What version of cass-operator are you using? The resolveAddress should not return the hostname in any case or try to add it to the seeds-service.

**Comment by sahid** [comment]
> What version of cass-operator are you using? The resolveAddress should not return the hostname in any case or try to add it to the seeds-service.

`image: datastax/cass-operator:1.6.0`

**Comment by burmanm** [comment]
That's your problem then, the hostname support was added in 1.7.1. As for multi-DC configuration, while it will accept the DNS Name, Cassandra itself does not. So it only resolves it to the IP, but does not notice if that IP changes. We're building a multi-DC solution that automates this process in the k8ssandra-operator. However, otherwise your approach works.

**Comment by sahid** [comment]
Thank you, I have verified with latest, it's working as expected.
