### ISSUE TITLE
K8SSAND-1160 ⁃ CassandraDatacenter topology for large deployments

### ISSUE THREAD

**Issue by sahid** [k8ssandra/cass-operator#255]
Hello, we are thinking about how should we use the resource CassandraDatacenter.

We have designed different solutions and would like inputs from the community about whether they make sense and in that case which one could be used.

Our first attempt was to gain in granularity. The current design using racks seems to be rigid. Example how to select during rolling restart which racks to be updated first. Or how to select which racks will have its size updated. The canary option seems to resolve some of the issues but not all when we are looking for more control over the DCs.

The other point is that how the controller will handle several CassandraDatacenter with more than hundred of nodes? Let's say a rolling restart is running on dc1, it seems that it will be not possible to do any operation on dc2 until the operation gets finished.

Finally, what will happen if the controller gets stuck, the current design means that all the failure domain won't be operable.

![topo1](https://i.imgur.com/7FpucFG.png)

In this first topology, we use a CassandraDatacenter per rack. It means that we have the granularity of managing rack per failure domain.

![topo2](https://i.imgur.com/05WlfSl.png)

In this topology, we configure cass-operator to listen events only on its own namespace. Meaning that we can have an operator running per failure domain.

The question is about your thinking of those two proposals and why CassandraDatacenter has been designed in that way and not per racks.

Thanks a lot,

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1160) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1160
┆priority: Medium

**Comment by jsanda** [comment]
Hi @sahid 

>The current design using racks seems to be rigid. Example how to select during rolling restart which racks to be updated first. Or how to select which racks will have its size updated.

It's true that there is no way to configure the operator for how it chooses racks in the scenarios. I can really see where that would be an issue in a scaling up situation. This would make for a nice enhancement.

>The other point is that how the controller will handle several CassandraDatacenter with more than hundred of nodes? Let's say a rolling restart is running on dc1, it seems that it will be not possible to do any operation on dc2 until the operation gets finished.

cass-operator manages each CassandraDatacenter independently, even if they are part of the same Cassandra cluster. It should be possible to perform operations on each of them.

If you are working with multi-DC clusters, you should check out [k8ssandra-operator](https://github.com/k8ssandra/k8ssandra-operator). Not only does it provide multi-DC support but it adds a number of other features including,

* multi-cluster (Cassandra cluster can span multiple k8s clusters)
* Stargate (data gateway for Cassandra)
* Reaper (repairs)
* Medusa (backup/restore)

**Comment by burmanm** [comment]
If @sahid is still interested in continuing these discussions, lets continue in the k8ssandra-operator repo. As @jsanda mentioned, it's our multi-DC solution.
