### ISSUE TITLE
K8SSAND-1166 ⁃ Auto Deletion of PVC's when Pods are scaled down is not desired in all times

### ISSUE THREAD

**Issue by Macfelon** [k8ssandra/cass-operator#256]
In decommision_node.go, the following code automatically just deletes the associated PVC's when a Pod is removed.

In an enterprise system, the reason we have PVC's is to maintain the current file states.

Can we have a property or tag that allows this behavior to be configurable?

`

```
func (rc *ReconciliationContext) cleanUpAfterDecommissionedPod(pod *corev1.Pod) result.ReconcileResult {
	rc.ReqLogger.Info("Scaling down statefulset")
	err := rc.RemoveDecommissionedPodFromSts(pod)
	if err != nil {
		return result.Error(err)
	}
	rc.ReqLogger.Info("Deleting pod PVCs")
	err = rc.DeletePodPvcs(pod)
	if err != nil {
		return result.Error(err)
	}

	dcPatch := client.MergeFrom(rc.Datacenter.DeepCopy())
	delete(rc.Datacenter.Status.NodeStatuses, pod.Name)

	err = rc.Client.Status().Patch(rc.Ctx, rc.Datacenter, dcPatch)
	if err != nil {
		rc.ReqLogger.Error(err, "error patching datacenter status to remove decommissioned pod from node status")
		return result.Error(err)
	}

	return nil
}
```

`

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1166) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1166
┆priority: Medium

**Comment by jsanda** [comment]
We could add a boolean flag in the `StorageConfig` struct (see [here](https://github.com/k8ssandra/cass-operator/blob/master/apis/cassandra/v1beta1/cassandradatacenter_types.go#L266)). What do you think?

**Comment by Macfelon** [comment]
Something like "PersistPVCs : true" and default or no entry == false?

Question, so when we rescale up lets just say for example, we have PVC k8ss-dc1-0, k8ss-dc1-1, k8ss-dc1-2, and we scale down, it leaves k8ss-dc1-2 pvc out there but is identified by it's hash, would it re-connect to that when we rescaled up to when it would create pod k8ss-dc1-2 again?

If so, I think that would be a great solution and additional functionality.

**Comment by jsanda** [comment]
Sorry, I got my wires crossed in my previous reply. I was thinking about deleting the CassandraDatacenter. cass-operator does not delete PVs when you delete a CassandraDatacenter. If you recreate the CassandraDatacenter, it will reuse those existing PVs.

For scaling down, I actually do think it makes sense to delete the PV. The node being decommissioned streams its data to other C* nodes. Token ownership may change. If you later scale back up, I don't you could simply give the new node that PV because the token ranges it will own may be different from the old node.

**Comment by burmanm** [comment]
The decommission part will be triggered on a downscaling of the Cassandra cluster. Thus, all the data will be migrated away from that PVC before it is deleted. I'm not entirely sure what state is expected to remain there. 

The PVCs are generated by StatefulSet controller as they are created with VolumeClaimTemplate, so it does not necessarily reconnect to those existing PVCs (StatefulSet could be scaled to another node for example).

The PersistentVolume's Reclaim Policy is one step also to prevent deleting the PVs.

**Comment by Macfelon** [comment]
> The decommission part will be triggered on a downscaling of the Cassandra cluster. Thus, all the data will be migrated away from that PVC before it is deleted. I'm not entirely sure what state is expected to remain there.
> 
> The PVCs are generated by StatefulSet controller as they are created with VolumeClaimTemplate, so it does not necessarily reconnect to those existing PVCs (StatefulSet could be scaled to another node for example).
> 
> The PersistentVolume's Reclaim Policy is one step also to prevent deleting the PVs.

So the PVC being removed is an expected and wanted behavior with cassandra given the replication in the rack that is automatic on scale down?

**Comment by burmanm** [comment]
Yes, that would be my opinion as the correct approach in Kubernetes environment with StatefulSets (implementation detail, but still). Leaving empty PVCs behind would not serve any purpose nor would it speed up scale-up.

**Comment by jsanda** [comment]
>Thus, all the data will be migrated away from that PVC before it is deleted. I'm not entirely sure what state is expected to remain there.

AFAIK the node streams its data but doesn't delete anything; however, outside of maybe auditing purposes, I don't think it would be very useful.

**Comment by Macfelon** [comment]
Ok, then what's the expected recovery process on a full cluster restart?  If there are no current nodes in existance, ss_tables would then all be empty?

**Comment by burmanm** [comment]
Do you mean in case of Kubernetes crash for example? It should start correctly (the configs are not deleted).

**Comment by Macfelon** [comment]
I understand in a crash, all the nodes are still there and kubernetes has memory on them, but I mean on an application restart or actually an application replace (delete, add new and even the DC delete and sync), it seems from our testing that all the PV's are being removed and new ones created.

**Comment by burmanm** [comment]
In case you delete the CassandraDatacenter, the PVCs are indeed deleted. Are you certain you actually want to delete the CassDc? If you simply want to stop it, there's a setting (Stopped), that will retain all the data.

With restart, I'm not entirely sure what you mean. How are you restarting (I assume you don't mean rolling restart) ?

**Comment by Macfelon** [comment]
> In case you delete the CassandraDatacenter, the PVCs are indeed deleted. Are you certain you actually want to delete the CassDc? If you simply want to stop it, there's a setting (Stopped), that will retain all the data.
> 
> With restart, I'm not entirely sure what you mean. How are you restarting (I assume you don't mean rolling restart) ?

Well, in our testing, we have been using Rancher and Argo primarily as our Kubes interface, and we have deleted the app, the DC, the deployments as part of that.  We're trying to find a way with the kubes to keep our PV's when we delete, or when we migrate from Bitnami to Datastax, and are looking for those options in this image set.  When we noticed the PV's were being deleted (they are not in our Bitnami and we are using our reclaim policy) to have that information persist so we don't lose our analytics or preloaded information in these scenarios.

It is entirely possible we are approaching our maintenance and migrations incorrectly though by doing things this way, and are open to understanding the best way to accomplish this for Datastax which is a 3x performance increase from Bitnami and why we're looking very hard into this.

**Comment by burmanm** [comment]
We do not delete the PVs themselves, only the claims. The PVs should exist if you've set the Reclaim policy to be `Retain`. That should keep the data. 

I do not sadly know Bitnami's solution to assist in the migration process. One possibility is to use multiple Datacenters to transfer the data and then decommission the old one.

**Comment by Macfelon** [comment]
> We do not delete the PVs themselves, only the claims. The PVs should exist if you've set the Reclaim policy to be `Retain`. That should keep the data.
> 
> I do not sadly know Bitnami's solution to assist in the migration process. One possibility is to use multiple Datacenters to transfer the data and then decommission the old one.

I do appreciate this discourse on the subject, it has been very helpful.  So the claims though are the hashed individual tagged entities, correct?  And when those are released, what configuration options are there in Datastax to reclaim/connect the existing PV's back into k8ss pods based on the scenarios listed previously?

**Comment by jsanda** [comment]
`Retain` is the default reclaim policy. If you delete a CassandraDatacenter and then create a new one with the same name, it will reuse those existing PVs.

**Comment by Macfelon** [comment]
Gentlemen, thank you immensely, it seems I do not need an additional option to accomplish the goals of retention and I'll close this one as redundant or not needed.

**Comment by sbbagal13** [comment]
@jsanda 
 I am using cass-operator on openshift and facing same issue. 
I updated the reclaimPolicy to Retain in my storage class but its retaining the PVs and not PVC's 
When I recreate the DC , Its creating new PV's and PVCs'
