### ISSUE TITLE
K8SSAND-1171 ⁃ How operator handles split brain

### ISSUE THREAD

**Issue by sahid** [k8ssandra/cass-operator#259]
Hello, I would like to understand whether there is any special attention when using k8ssandra during a split-brain scenario?

Also I have noticed the /probes/cluster, I would imagine this could help during such scenario, unfortunately I did not find a lot of resources around. What will happen if this API returns an error, could you share some pointers?

https://github.com/k8ssandra/management-api-for-apache-cassandra/blob/master/management-api-server/src/main/java/com/datastax/mgmtapi/resources/K8OperatorResources.java#L103

Thanks,
s.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1171) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1171
┆priority: Medium

**Comment by jsanda** [comment]
The operator only proceeds to start C* nodes when that check passes. See [here](https://github.com/k8ssandra/cass-operator/blob/master/pkg/reconciliation/reconcile_racks.go#L614).
