### ISSUE TITLE
K8SSAND-1234 ⁃ Adopt a more structured `Image` type

### ISSUE THREAD

**Issue by Miles-Garnsey** [k8ssandra/cass-operator#268]
**What is missing?**

The fields `ConfigBuilderImage` and `SystemLoggerImage` are currently string types, which causes some [complications](https://github.com/k8ssandra/k8ssandra-operator/issues/378#issuecomment-1034353315) when passing values down into cass-operator from k8ssandra-operator. 

It would be ideal if they were structs as this would allow us to take advantage of the kubebuilder `+kubebuilder:default` struct tags and allow for a more intuitive user experience.

**Why do we need it?**

**User friendliness**

Users probably expect to be able to override just one element of the docker image location (likely repository or registry). In the current setup, they cannot do this without overriding the whole image field, which fixes them to specific registries, repositories, image and tag and is another thing they then need to manage at upgrade-time.

**Ability to use default struct tag**

The ability to use the `+kubebuilder:default` struct tag would be helpful, as it would allow us to control the images from a single location in a more declarative way, rather than setting these defaults using custom logic in the controllers.

**Enhanced compatibility with k8ssandra operator**

K8ssandra-operator uses a structured `Image` field in several [locations](https://github.com/k8ssandra/k8ssandra-operator/issues/378) and it would be a cleaner integration if this type was shared between both projects.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1234) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1234
┆priority: Medium

**Comment by burmanm** [comment]
cass-operator uses ImageConfig to achieve repository, pull secrets, version modifications. That method is the recommended approach to modifying these images.

These fields should be removed in the future and as such should not have modifications to their behavior anymore.

**Comment by Miles-Garnsey** [comment]
Should ConfigBuilderImage and SystemLoggerImage be marked [deprecated](https://github.com/kubernetes-sigs/kubebuilder/issues/2116) immediately then?

I'll need to go back and try to understand what you're doing with ImageConfig. I'll tag you in the corresponding ticket on k8ssandra-operator to see if your comments above change the approach we need to take there too.

**Comment by Miles-Garnsey** [comment]
This is a duplicate of #294. Closing.
