### ISSUE TITLE
Create OLM bundle integration-test

### ISSUE THREAD

**Issue by burmanm** [k8ssandra/cass-operator#273]
**What is missing?**
We do not verify that the bundle we create can be deployed with OLM at all stages (it's done manually before release). This needs to be ensured so that we can push the output correctly to operatorHub.

Also, fix CassandraTask alm-example:

```
WARN[0000] Warning: Value control.k8ssandra.io/v1alpha1, Kind=CassandraTask: provided API should have an example annotation 
```

**Why do we need it?**
We want to automate the output to OperatorHub, the release process shouldn't be manual and we want to ensure that our operator conforms to the current bundle requirements.

**Comment by jdonenine** [comment]
Closing to try to fix the sync with Unito that didn't seem to happen.
