### ISSUE TITLE
K8SSAND-1293 ⁃ Deleting DC deletes PVC's and not re-attaching same PV after recreated with same details in openshift

### ISSUE THREAD

**Issue by sbbagal13** [k8ssandra/cass-operator#285]
Hi All, I am using cass-operator on Openshift (Installed from operator hub) 
When I create DC with 3 nodes , it creates 3 PV's bind with 3 PVC's , All works as expected 

Issue: When I delete DC then PVC's are getting deleted, PV's are still available with Released status. As per some closed issues, If I create same DC again (With no change) it should re-attach existing PV's and data should be Intact. But I see everytime new PV's are getting created and earlier PV's are in hanging state of no use. I tried to bound existing PV's while recreating DC but no luck. 

Is this the default behavior or do we have solution for it?

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1293) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1293
┆priority: Medium

**Comment by adejanovski** [comment]
This is the default behavior and we think that's how things should work.
If a DC is deleted, and then recreated, we'll want it to start fresh and have it rebuilt from the existing DCs.
If the old PVs were reattached to the instances, you would have an old state that is loaded into this newly created DC, creating inconsistencies and preventing a rebuild.
If you want to stop a DC and then restart it while retaining its state, you can use set `stopped` field to `true` in the cassdc spec, and then `false` when you want to bring it back.
