### ISSUE TITLE
K8SSAND-1413 ⁃ Update to ginkgo v2

### ISSUE THREAD

**Issue by burmanm** [k8ssandra/cass-operator#291]
**What is missing?**
ginkgo v1 is deprecated. We should update tests to ginkgo v2.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1413) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1413
┆priority: Medium

**Comment by jsanda** [comment]
What about migrating tests to use Go's native testing?

**Comment by burmanm** [comment]
Removing ginkgo + gomega for require/assert + testing.T is quite a lot of work. There's large amount of ginkgo tests already in the project and updating just to v2 should not be a large task. 

Even if moving away from ginkgo later, I think it would make sense to ensure we have ginkgo v2 tests before that (and maybe some cleanup of tests).
