### ISSUE TITLE
K8SSAND-1347 ⁃ EBS volumes get deleted automatically during a node migration

### ISSUE THREAD

**Issue by jakerobb** [k8ssandra/cass-operator#302]
**What happened?**
We were moving our cass-operator-managed DSE cluster on EKS to bigger nodes. It's an older cluster, with DSE 6.8.9 and cass-operator 1.5.1. Three racks, one node each, and an autoscaling group controlling each rack. One node was in a bad state, unable to start. Here's how it went:

1. Modify all three ASGs with the new instance type and desired replicas=2. This left the existing instances in place and created new ones with the new instance type. Wait for the new instances to join the EKS cluster.
1. `kubectl drain` one of the old nodes. The pod automatically gets rescheduled on the new node.
1.  The pod is unable to bind to its PersistentVolume because there is already a PVC for the old node. We deleted the PVC.
1.  The PVC is recreated for the new node and the pod progresses to `Ready-to-Start`, then hangs there (which is another issue I'll report separately.)
1. We realized the deadlocked state we had created (should have replaced the bad node first!) and bailed on the rolling update. We set `stopped: true` in the CassandraDatacenter, drained all three nodes, and deleted their PVCs.
1. Set `stopped: false` and wait. After a few minutes, all three pods reported Ready, and things looked healthy.
1. We tried using our application which depends on this database. Still broken! Upon investigation, we had a brand-new cluster with no roles, no authentication configuration, none of our keyspaces, none of our data. :grimacing:

**Did you expect to see something different?**
I expected our data to be there!

**How to reproduce it (as minimally and precisely as possible)**:

1. Spin up a cluster using EBS-backed volumes. Give it some data.
1. Set `stopped: true`
1. Wait for graceful shutdown; delete the PVCs
1. Set `stopped: false`
1. Wait for cluster to come back up.
1. That data you stored in step 1? It's gone now.

**Anything else we need to know?**:
This happened because the [`server-storage` StorageClass created by cass-operator has `reclaimPolicy: Delete`](https://github.com/k8ssandra/cass-operator/blob/master/operator/k8s-flavors/eks/storage.yaml), so as soon as we removed the PVCs, EBS deleted our volumes. The bug is here, but similar bugs may also exist in the equivalent templates for other providers; I haven't checked!

Unfortunately, we weren't so thoughtful as to have created snapshots of the volumes prior to this activity, but luckily we did have our keyspaces backed up to S3 (and, thank the stars, it was only dev)! We're back in business now, but this created quite the scare and took several hours to resolve.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1347) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1347
┆priority: Medium

**Comment by jimdickinson** [comment]
I would strongly advise against ever deleting the PVCs if you still need the data.

**Comment by jsanda** [comment]
@jakerobb a couple things:

* The helm chart that was used to deploy cass-operator and the storage class in question lives neither in this repo nor in the k8ssandra repo 🙂  
* Given the comment from @jimdickinson it is debatable whether or not `reclaimPolicy: Delete` should be considered a bug. Not saying I agree or disagree but worth noting. 

It would be great to continue discussion on this and get some operational insights but I am going to close this to avoid any confusion about work needing to be done in this repo.

**Comment by jsanda** [comment]
You should be able to unbind the volume from the claim which would then allow you to bind it to a different claim.

**Comment by jsanda** [comment]
There is another thing I failed to note on why I closed this. cass-operator doesn't create StorageClasses, nor does the k8ssandra/cass-operator Helm chart.

**Comment by jsanda** [comment]
Another thing worth noting :) A PV has a `persistentVolumeReclaimPolicy` property. I believe its value is derived from the StorageClass. If memory serves I believe its value needs to be changed to `Retain` when you unbind it from its claim; otherwise, it will get deleted.

**Comment by jakerobb** [comment]
Noted! Some followup:

1. I did some cursory research yesterday on how to unbind a PVC without deleting it, and came up empty so far. If anyone here knows how to do it, I would love a pointer!

2. If cass-operator starts up a pod, and that pod gets stuck in Pending because it's on a new node and the PVC is already bound, should/could it be cass-operator's responsibility to fix it? I imagine we would have to somehow inform cass-operator that a node replacement was in flight; I don't know if there's a suitable mechanism to do that. I'd love your thoughts on this.
