### ISSUE TITLE
K8SSAND-1369 ⁃ Certificate rotation for cass-operator

### ISSUE THREAD

**Issue by Miles-Garnsey** [k8ssandra/cass-operator#308]
**What is missing?**

CA certificates cannot currently be rotated without downtime for cass-operator deployed clusters. 

We should enable the injection of both old and new certificates during a grace period so that CAs can be rotated smoothly.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1369) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1369
┆priority: Medium

**Comment by jsanda** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/K8ssandra-Grooming-623b197f1fcd4800110540ef/issues/k8ssandra/cass-operator/308?planning-poker) with ZenHub @burmanm @Miles-Garnsey

**Comment by Miles-Garnsey** [comment]
This one is relatively complex and may benefit from a preliminary research ticket. Estimates are as follows:

* 2 days on design work to determine how this needs to work and socialise (as there are a few options and the [design doc](https://github.com/k8ssandra/k8ssandra-operator/pull/432) has not been approved+merged.)
* 4 days to implement a layer of indirection so that a change to the certificates triggers a copy of the existing encryption materials before commencing rotation.
* 4 days to implement features relating to injecting encryption materials into the truststore and combining them. 

Note that I've put estimates at the higher end of the range here but I think they will be roughly accurate once we account for the need for some nuanced test cases.

**Comment by burmanm** [comment]
This work was superseded by other CA work.
