### ISSUE TITLE
K8SSAND-1410 ⁃ ScalingUp Status is not always removed

### ISSUE THREAD

**Issue by burmanm** [k8ssandra/cass-operator#311]
**What happened?**
While running scale_up integration test, I've noticed that the second / third cleanup task is not always created as it seems the DatacenterController thinks there's still an active one (and as such, no new one is required). There are few indicators why this could be happening:

```
1.6488026926732535e+09	ERROR	controller.cassandratask	Reconciler error	{"reconciler group": "control.k8ssandra.io", "reconciler kind": "CassandraTask", "name": "cleanup-1648802692", "namespace": "test-scale-up", "error": "Operation cannot be fulfilled on cassandratasks.control.k8ssandra.io \"cleanup-1648802692\": the object has been modified; please apply your changes to the latest version and try again"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:266
```

That task did complete (the controller was able to handle it), but it indicates we have some concurrent update / missing refresh. The next one completed without issues, but on this run, the third one was never created - but there's no logging to indicate why this might have happened.

Sadly, we don't have CassandraDatacenter status logged in the test framework, so tracking why that might have happened is difficult. Tracking this in #312 

From further debugging, it seems to be that CassandraDatacenter stays in "ScalingUp" and updating and that's why CassandraTask is never created:

```yaml
  - lastTransitionTime: "2022-04-01T09:59:05Z"
    message: ""
    reason: ""
    status: "True"
    type: ScalingUp
  - lastTransitionTime: "2022-04-01T10:01:58Z"
    message: ""
    reason: ""
    status: "True"
    type: Updating
```

Yet there's no action going on in the cass-operator, since:

```
1.6488073383268092e+09  INFO    controllers.CassandraDatacenter.cassandradatacenter_controller.controller.cassandradatacenter-controller        All StatefulSets should now be reconciled.{"reconciler group": "cassandra.datastax.com", "reconciler kind": "CassandraDatacenter", "name": "dc2", "namespace": "test-scale-up", "namespace": "test-scale-up", "datacenterName": "dc2", "clusterName": "cluster2"}
```

**Did you expect to see something different?**

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Cass Operator version:

    `Insert image tag or Git SHA here`
    
    * Kubernetes version information:    `kubectl version`
    * Kubernetes cluster kind:```
insert how you created your cluster: kops, bootkube, etc.
```

* Manifests:

```
insert manifests relevant to the issue
```

* Cass Operator Logs:

```
insert Cass Operator logs relevant to the issue here
```

**Anything else we need to know?**:



┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1410) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1410
┆priority: Medium

**Comment by jsanda** [comment]
@burmanm are you saying that subsequent CassandraTasks do not get created because the ScalingUp status doesn't get cleared, which means the subsequent cleanup jobs do not happen? 

Am I correct in thinking that the cleanup tasks are created per C* node?

**Comment by burmanm** [comment]
No, single task per scale up request, node count does not matter. 

But yes, they were not created because the ScalingUp was not removed.
