### ISSUE TITLE
K8SSAND-1420 ⁃ cass-operator regexp will not allow setting version to Cassandra 4.1

### ISSUE THREAD

**Issue by burmanm** [k8ssandra/cass-operator#313]
**What is missing?**
Next version of Cassandra will be 4.1, however our regexp only allows 4.0.* currently.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1420) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1420
┆priority: Medium

**Comment by bradfordcp** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/K8ssandra-Grooming-623b197f1fcd4800110540ef/issues/k8ssandra/cass-operator/313?planning-poker) with ZenHub @burmanm @jsanda
