### ISSUE TITLE
K8SSAND-1505 ⁃ manifest yaml file?

### ISSUE THREAD

**Issue by shengzhizhou** [k8ssandra/cass-operator#331]
Is there any manifest yaml file I can use directly for latest version, instead of kustomize build entire folder? I found this [documentation](https://docs.datastax.com/en/cass-operator/doc/cass-operator/cassOperatorGettingStarted.html) on datastax but I need latest version, because cass-operator 1.7.1 doesn't support on kubectl 1.23. Thanks.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1505) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1505
┆priority: Medium

**Comment by jsanda** [comment]
You can install via kustomize or with helm. The helm chart lives [here](https://github.com/k8ssandra/k8ssandra/tree/main/charts/cass-operator).  Here are a couple examples with kustomize

Install 1.10.3:
```console
k apply -k build github.com/k8sandra/cass-operator/config/deployments/default\?ref=v1.10.3 
```
Install 1.10.3 configured with cluster scope:
```console
k apply -k build github.com/k8sandra/cass-operator/config/deployments/cluster\?ref=v1.10.3 
```

**Comment by shengzhizhou** [comment]
Hi, But I have to customize some code to fit our kubernetes cluster, so I may have to bring down entire folder and run them. If there's one manifest file, would be a lot easier. thanks.

**Comment by burmanm** [comment]
You can build it locally also with just kustomize:

```kustomize build 'github.com/k8sandra/cass-operator/config/deployments/default?ref=v1.10.4' > manifest.yaml```

**Comment by shengzhizhou** [comment]
yeah, I tried but got "Error: git cmd = 'C:\Program Files\Git\cmd\git.exe fetch --depth=1 origin v1.10.4': exit status 128". Let me bring down entire folder and build locally.

**Comment by shengzhizhou** [comment]
okay, I got the manifest now, thanks
