### ISSUE TITLE
K8SSAND-1508 ⁃ hostpath storage

### ISSUE THREAD

**Issue by shengzhizhou** [k8ssandra/cass-operator#333]
Is there any way I can change CassandraDatacenter storageconfig to use VolumeMount with hostpath? Our kubernetes cluster doesn't fully support storage class or persistentvolume right now. 
Also for testing I removed storageconfig from required, but cass-operator log still show error: "StorageConfig.cassandraDataVolumeClaimSpec is required" How can I remove it correctly, just for testing? Thanks.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1508) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1508
┆priority: Medium

**Comment by burmanm** [comment]
You can use hostPath, but you need to have a storageClass to use it with. rancher.io/local-path is a better one than the one shipped with Kubernetes:

https://github.com/rancher/local-path-provisioner

The StorageConfig requirements come from probably webhook and elsewhere in the reconciliation logic. It might require quite a bit of changes to get rid of that requirement.

**Comment by shengzhizhou** [comment]
Hi, what's meaning behind this error: "CassandraDatacenter write rejected, attempted to change storageConfig". I comment out the StorageConfig from both cass-oeprator and CassandraDatacenter.

**Comment by shengzhizhou** [comment]
Even I installed [local-path-provisioner](https://github.com/rancher/local-path-provisioner) and created a storageclass, uncomment StorageConfig, it still show same error  "CassandraDatacenter write rejected, attempted to change storageConfig".

**Comment by burmanm** [comment]
That is entirely different case, one can't modify the existing CassandraDatacenter's StorageConfig that way.

**Comment by shengzhizhou** [comment]
sorry, I just delete the CassandraDatacenter and recreated, seems the pod is creating now but has some error creating first one about server-system-logger. 
And the other pods shows: "0/3 nodes are available: 1 Insufficient cpu, 1 node(s) didn't match Pod's node affinity/selector, 1 node(s) had taint {CriticalAddonsOnly: true}, that the pod didn't tolerate.". Is it because the first one isn't created so that other pods won't start creating?

**Comment by shengzhizhou** [comment]
Updates:
After I set dockerImageRunsAsCassandra to true, server-system-logger is created now, the first node is fully running now. But the other node still pending because Insufficient cpu error. I tried to set resources as low as possible like "memory: 100m cpu: 100m", and the node usage is not full either: "CPU Used 0.59 of 4 /15%; MEMORY Used 4.71 of 7.56 GiB / 62%". Is it normal? Thanks.

**Comment by shengzhizhou** [comment]
Another question:
I try to run cqlsh in cluster1-dc1-rack1-sts-0 with cluster1-superuser secrets but it keeps show username/password are incorrect. I did decode the password from cluster1-superuser secrets and use cluster1-superuser as username, still failed. Thanks for answering.

**Comment by shengzhizhou** [comment]
More details:
The second node and third node shows error: "0/3 nodes are available: 1 Insufficient cpu, 1 node(s) didn't match Pod's node affinity/selector, 1 node(s) had taint {CriticalAddonsOnly: true}, that the pod didn't tolerate." Is it because lack of resources in our kubernetes cluster?
I used following code to deploy CassandraDatacenter:
```kind: CassandraDatacenter
metadata:
  name: dc1
spec:
  nodeSelector:
    kubernetes.io/os: linux
  clusterName: cluster1
  serverType: cassandra
  serverVersion: "4.0.3"
  managementApiAuth:
    insecure: {}
  size: 3
  storageConfig:
      cassandraDataVolumeClaimSpec:
        storageClassName: server-storage
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  dockerImageRunsAsCassandra: true
  resources:
    requests:
      memory: 100m
      cpu: 100m
  racks:
    - name: rack1
  config:
    jvm-server-options:
      initial_heap_size: "100M"
      max_heap_size: "100M"
    cassandra-yaml:
      num_tokens: 16
      authenticator: PasswordAuthenticator
      authorizer: CassandraAuthorizer
      role_manager: CassandraRoleManager 
```

**Comment by burmanm** [comment]
Insufficient CPU resources is coming from your Kubernetes cluster, not from cass-operator. You need to check your resources allocations in the node (or if you have additional restrictions, like namespace etc).

As for your superuser, it all depends if you've changed that password or not. That's just the initially created secret. You might want to drop in to the [k8ssandra Discord](https://discord.gg/qP5tAt6Uwt) for more support, the issues are a bad place to discuss these.

**Comment by shengzhizhou** [comment]
thanks
