### ISSUE TITLE
K8SSAND-1527 ⁃ Diagnose potential incompatibility with CDC agent

### ISSUE THREAD

**Issue by Miles-Garnsey** [k8ssandra/cass-operator#336]
**What happened?**

According to [this FAQ](https://docs.datastax.com/en/cdc-for-cassandra/cdc-apache-cassandra/1.0.3/faqs.html) the DataStax CDC agent should interoperate with cass-operator. However, when I tried to reproduce the integration test demonstrating the compatibility, I wasn't able to successfully get events to feed into a Pulsar deployment.

Initially we had issues in two areas:

1. The management API needs to be added to the classpath so that the custom SeedProvider class we use (K8SeedProvider) is available to the CDC agent.
1. The CDC agent needs to be started after the management API, or management API doesn't start.

While we were able to resolve those two problems, we still aren't seeing events output to the Pulsar topic.

When I check the logs, I can see:

1. The CDC agent starts
1. Management API returns 200s in response to liveness/readiness probes.
1. CDC is enabled on the table created in Cassandra.
1. The data is being flushed (using `nodetool flush`) and then cassandra-stress is being used to flood the commitlogs.

**Did you expect to see something different?**

These conditions should lead to the cdc agent picking up the flushed commitlogs and sending them to the Pulsar connector, but we aren't seeing the events appear in Pulsar.

We are currently waiting on the Pulsar team to help us troubleshoot. This ticket to track any further work as it comes through.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1527) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1527
┆priority: Medium

**Comment by burmanm** [comment]
This should be filed under https://github.com/datastax/cdc-apache-cassandra/issues

**Comment by Miles-Garnsey** [comment]
> This should be filed under https://github.com/datastax/cdc-apache-cassandra/issues

I don't know about that. It is an interaction between the management API/cass-operator and CDC agent. 

I don't know specifically where the problem is between the three components, but it is delaying the integration of CDC into cass-operator, which is why I think it makes the most sense to raise here.

**Comment by burmanm** [comment]
It just feels odd to have a bug report for a feature we don't yet have. Wouldn't this fall under the initial implementation ticket?

**Comment by Miles-Garnsey** [comment]
I'm only splitting it because tickets should be < 5 days (from previous discussion). If the initial implementation was a solid 6-7 days, writing the tests and trying to get this problem resolved has taken a good further 6-7. 

I was reluctant to split writing the tests from the initial implementation (because an implementation should just always include tests). But that was the other alternative. 

So we can either have:

* Two tickets, one for tests and one for functionality.
* Two tickets, one for functionality + (implicitly) tests, and one for diagnosing failure to CDC/MAAC failure to interoperate as expected.

Truth be told I don't feel I've managed this process very well overall. A combination of the move to Zenhub and a lot of unexpected additional work being required has meant that the reality of the implementation has not matched my planning.

**Comment by Miles-Garnsey** [comment]
Update:

* The Pulsar team has advised that only versions of DSE > 6.8.16 are compatible with the CDC agent. The tests they had originally used 6.8.14. 
* We now have events outputting to the topic as expected. 
* I will now try to run the same tests with OSS Cassandra. If that fails, I'll refer the failure back to the Pulsar team and also try to diagnose what's happening in the JVM.

**Comment by Miles-Garnsey** [comment]
Having upgraded to the CDC agent 2.0.0, it appears that I can now see data feeding into the Pulsar topic for both OSS Cassandra and DSE.

This places the CDC agent out of sync with the current Docker Pulsar docker images (which include 1.0.3 of the corresponding connector .nar). Hopefully this will not cause additional problems.

I am working to build a test utility that will count the records to ensure that they are all appearing.

**Comment by Miles-Garnsey** [comment]
I am still working to verify that -

1 All mutations are appearing on the Pulsar topic, and;
2. That they are encoded correctly. 

The tests originally provided by the streaming folks use `key.converter` and `value.converter` Pulsar connector options to convert incoming records to Avro. I have tried to read these using both Python and (third party) Scala client libraries but have not been successful so far. 

I've raised an [issue](https://github.com/CleverCloud/pulsar4s/issues/431) on the third party Scala library to ask for clarification on how to use Avro in conjunction with their client. I've been in touch with the streaming team regarding the Python client library and how this should be used. 

I will now move on to trying the Java client library, since that appears to be the best documented first-party library available.

**Comment by Miles-Garnsey** [comment]
Some additional experimentation yielded success. I can confirm that all mutations I throw at Cassandra now appear in the Pulsar topic, and do appear to be correctly encoded (I removed `key.converter` and `value.converter` and added a slightly obscure config option).

Closing this ticket, as all problems have now been diagnosed and worked around.
