### ISSUE TITLE
K8SSAND-1530 ⁃ Add DSE/OSS Cassandra validation for CDC configs

### ISSUE THREAD

**Issue by Miles-Garnsey** [k8ssandra/cass-operator#337]
**What is missing?**

The first iteration of the CDC reconciliation logic doesn't take account of the fact that DSE deployments won't support CDC until the CDC agent is built into a DSE image. 

We should provide validation through either/both of:

1. The validating webhook.
1. The reconciliation logic itself.

When CDC is requested for a DSE deployment this is an error.

**Why do we need it?**

DSE deployments currently use the official DataStax DSE images. As of now these do not include the CDC agent and attempts to enable CDC in these images will cause DSE to fail to start.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1530) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1530
┆priority: Medium

**Comment by burmanm** [comment]
This is no longer valid.
