### ISSUE TITLE
K8SSAND-1588 ⁃ Support k8s v1.19+

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/cass-operator#352]
cass-operator v1.11.0 dropped support for versions before v1.21.
As there are many clusters running on v1.19 and v1.20, it would be nice to provide support for those versions as well.
We'd need to identify which APIs we're using that only exist in v1.21+ and see if we can use an alternate API for versions before that (or disable the features they provide).

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1588) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1588
┆priority: Medium

**Comment by adejanovski** [comment]
@burmanm, wdyt?

**Comment by burmanm** [comment]
That's called 1.10.4

**Comment by adejanovski** [comment]
The question is around what would be the effort to get 1.19 or 1.20 support again in the v1.11+ releases.
Is it plain impossible? Is it a lot of efforts?

**Comment by burmanm** [comment]
It would be, and would make no sense. This was actually discussed earlier in the Slack, but in the end - supporting old unsupported versions of Kube means no support for newer versions of Kube.

**Comment by jsanda** [comment]
>That's called 1.10.4

I made this same suggestion recently. As it is we may need to maintain the 1.10 brach for while to support some folks internally.

**Comment by burmanm** [comment]
Should be no problem to backport bug fixes to 1.10 branch. Currently it has all of them from 1.11 (rest of 1.11 is mostly to support newer Kube and provide Openshift 4.9 support)
