### ISSUE TITLE
K8SSAND-1592 ⁃ Add checks to detect name conflicts between containers and additional ones

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/cass-operator#353]
Following up on the conversation of [this K8ssandra-operator issue](https://github.com/k8ssandra/k8ssandra-operator/issues/569) we would need to add some checks to prevent entries from `AdditionalContainers`, `AdditionalInitContainers` and `AdditionalVolumes` to conflict with the entries created by cass-operator itself :

* init-containers: `server-config-init`
* containers: `cassandra` and `server-system-logger`
* volumes: `server-data`, `server-config`, `server-logs` and `encryption-cred-storage`

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1592) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1592
┆priority: Medium

**Comment by adutra** [comment]
It's not just about adding checks imo. It's also about what to do when the pod template spec contains containers and volumes that cass-operator manages (the ones you listed). Currently cass-operator tries to merge what the user passed with what it needs to set. IMHO, it's a feature, not a bug :-)

**Comment by jsanda** [comment]
Good point about the merge functionality. Given that I don't think it makes sense to add these checks.

**Comment by burmanm** [comment]
The merge functionality is used even in the integration tests, it's a way to modify certain properties. Do not break that.
