### ISSUE TITLE
K8SSAND-1635 ⁃ Expose customizable metric filters

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/cass-operator#361]
**What is missing?**
cass-operator creates Cassandra pods with images that contain MCAC for metrics extraction.
Currently the filters can be set as an env variable in the cassandra container, but cass-operator doesn't allow to cleanly set them up without modifying the PodTemplateSpec (which is how k8ssandra-operator creates them).

**Why do we need it?**
Cassandra exposes a lot of metrics which may need to be filtered if there are many tables in the cluster, as scraping may not keep up then.

* Cass Operator version:

    `v1.11.0`
    
    **Anything else we need to know?**:

Filters are expected to be passed in the same env variable named `METRIC_FILTERS` and should be separated by a space.
Here are the default filters from K8ssandra 1.x:

```
METRIC_FILTERS: deny:org.apache.cassandra.metrics.Table deny:org.apache.cassandra.metrics.table allow:org.apache.cassandra.metrics.table.live_ss_table_count allow:org.apache.cassandra.metrics.Table.LiveSSTableCount allow:org.apache.cassandra.metrics.table.live_disk_space_used allow:org.apache.cassandra.metrics.table.LiveDiskSpaceUsed allow:org.apache.cassandra.metrics.Table.Pending allow:org.apache.cassandra.metrics.Table.Memtable allow:org.apache.cassandra.metrics.Table.Compaction allow:org.apache.cassandra.metrics.table.read allow:org.apache.cassandra.metrics.table.write allow:org.apache.cassandra.metrics.table.range allow:org.apache.cassandra.metrics.table.coordinator allow:org.apache.cassandra.metrics.table.dropped_mutations
```

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1635) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1635
┆priority: Medium

**Comment by burmanm** [comment]
Not valid anymore for new /metrics endpoint, closing.
