### ISSUE TITLE
K8SSAND-1652 ⁃ Use httpGet as liveness / readiness check instead of wget and add a timeout

### ISSUE THREAD

**Issue by burmanm** [k8ssandra/cass-operator#369]
**What is missing?**
We use wget to do the liveness / readiness check for the management-api, without timeout. This might cause the wget calls to hang and they will never return.

There's no reason to do it with wget anymore, Kubernetes these days has httpGet support for the liveness / readiness checks and we should take advantage of that. Management-api should have those resources always available without the need for TLS calls.

**Why do we need it?**

**Environment**

* Cass Operator version:

    `Insert image tag or Git SHA here`
    
    **Anything else we need to know?**:

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1652) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-1652
┆priority: Medium
┆Link To Issue: https://k8ssandra.atlassian.net/browse/K8SSAND-1652

**Comment by jsanda** [comment]
The docs for corev1.Probe say the if not specified the `TimeoutSeconds` field defaults to one second. Given that we have seen issues with the wget processes accumulating it makes me wonder if that timeout simply applies to the kubelet.

Maybe the kubelet doesn't do anything with respect to cleaning up the exec handler.
