### ISSUE TITLE
K8SSAND-1668 ⁃ Investigate flaky CDC tests

### ISSUE THREAD

**Issue by Miles-Garnsey** [k8ssandra/cass-operator#378]
**What happened?**

burmanm has reported that the CDC tests are regularly failing on `master`.

**Did you expect to see something different?**

The tests should not be flaky.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1668) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1668
┆priority: Medium

**Comment by Miles-Garnsey** [comment]
I'm investigating this now. I've been unable to replicate the failures locally, the tests pass consistently.

I think this is related to a timing issue on the Pulsar side. This is being tracked via an internal ticket. 

I did originally see some issues of this nature, but added calls to `thread.sleep` for 20 seconds in between schema creation/connector creation, and between connector creation/data insertion. This resolved the problem locally. Clearly this pause is not sufficient for GHA though, due to it being slower.

I am going to try removing the sleep calls. Then I'm going to experiment to see if waiting for schema agreement in between each test step in the testutils application leads to more consistent results. 

If that fails, I'll try adding a longer sleep, but I expect this will still lead to quite regular flakes, since we can't control timing between the three systems involved here.

**Comment by Miles-Garnsey** [comment]
My attempts to use `checkSchemaAgreement()` to avoid the timing issues were unsuccessful.

Instead, I've had to increase the `thread.sleep()` calls to 2 minutes. This results in the tests consistently passing on the first attempt locally. I will attempt to re-run on GHA to see if it fixes the issue there too.

**Comment by Miles-Garnsey** [comment]
This is resolved.

**Comment by Miles-Garnsey** [comment]
Can whoever re-opened this please leave a comment so we know who it was? Right now it just looks like Unito re-opened it, and I doubt whether the bot will be able to answer my questions to diagnose the issue.

**Comment by adejanovski** [comment]
Yeah, I blame Skynet. I'll go ahead and close this again :)
