### ISSUE TITLE
K8SSAND-1710 ⁃ Ability to specify the execution order of multi-pod CassandraTasks

### ISSUE THREAD

**Issue by adutra** [k8ssandra/cass-operator#389]
**What is missing?**

When a CassandraTask targets more than a single pod, it executes tasks in parallel on all pods. We need more fine-grained execution orders, e.g. if a task puts the nodes on pressure, then we should execute the task on all pods from one rack only, then move to the next rack, etc.

**Why do we need it?**

In order to avoid overloading the entire DC.

**Environment**

* Cass Operator version:

    `Insert image tag or Git SHA here`
    
    **Anything else we need to know?**:

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1710) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1710
┆priority: Medium

**Comment by burmanm** [comment]
I'm not entirely sure what this ticket was about, but this is the process it's doing right now. They're sorted to defined order (per rack):

```go
	sort.Slice(dcPods, func(i, j int) bool {
		rackI := dcPods[i].Labels[cassapi.RackLabel]
		rackJ := dcPods[j].Labels[cassapi.RackLabel]

		if rackI != rackJ {
			return rackI < rackJ
		}

		return dcPods[i].Name < dcPods[j].Name
	})
```

And then only one pod can be executing at the same time.
