### ISSUE TITLE
K8SSAND-1756 ⁃ make cass-operator multi-tenant compliant with opinionated k8s distributions

### ISSUE THREAD

**Issue by rspierz** [k8ssandra/cass-operator#400]
For clusters like openshift that assign UID at the namespace level it requires images to follow these rules.

https://docs.openshift.com/container-platform/4.10/openshift_images/create-images.html#images-create-guide-openshift_create-images 

Can the cass-operator image be updated to support random UID with the details above? This would provide a better security posture as well for multi-tenant kuberentes environments where UIDs overlapping on shared infra can be a security risk.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1756) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1756
┆priority: Medium

**Comment by burmanm** [comment]
This is already fixed in the current versions.
