### ISSUE TITLE
K8SSAND-1833 ⁃ Add e2e test for cleanup CassandraTask

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/cass-operator#427]
**What happened?**
There is no e2e test for running cleanup via a CassandraTask.

* Cass Operator version:

    `v1.13.0`
    
    

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1833) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1833
┆priority: Medium

**Comment by burmanm** [comment]
There is, it's tested as part of the scale_up tests, such as: https://github.com/k8ssandra/cass-operator/blob/master/tests/scale_up/scale_up_suite_test.go
