### ISSUE TITLE
K8SSAND-1834 ⁃ Add e2e test for running scrub CassandraTask

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/cass-operator#428]
**What happened?**
There is no e2e test for running scrub via a CassandraTask.

* Cass Operator version:

    `v1.13.0`
    
    

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1834) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1834
┆priority: Medium

**Comment by burmanm** [comment]
There is no scrub feature.
