### ISSUE TITLE
K8SSAND-1835 ⁃ Add e2e test for running compaction CassandraTask

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/cass-operator#429]
**What happened?**
There is no e2e test for running compaction via a CassandraTask.

* Cass Operator version:

    `v1.13.0`
    
    

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1835) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1835
┆priority: Medium

**Comment by burmanm** [comment]
There is no compaction CassandraTask either. So why would a e2e test missing be a bug of a feature that we don't have?
