### ISSUE TITLE
K8SSAND-1879 ⁃ Implement a CassandraTask for moving single-token nodes

### ISSUE THREAD

**Issue by adutra** [k8ssandra/cass-operator#441]
**What is missing?**

A CassandraTask to run `nodetool move`:

https://cassandra.apache.org/doc/latest/cassandra/tools/nodetool/move.html

**Why do we need it?**

This will be useful when rebalancing unbalanced clusters.

**Anything else we need to know?**:

We will need https://github.com/k8ssandra/management-api-for-apache-cassandra/issues/219 implemented first.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1879) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-1879
┆Priority: Medium
┆Link To Issue: https://k8ssandra.atlassian.net/browse/K8SSAND-1879

**Comment by burmanm** [comment]
Shouldn't the entire rebalance be implemented instead of single move? In which case a single move is issued?

**Comment by adutra** [comment]
I was planning to create another ticket for rebalancing the entire cluster. I don't have strong opinions but it feels to me that people could use the move task to move individual nodes, e.g. if they already have a good token distribution that they computed manually and want to use it.
