### ISSUE TITLE
Are the scenarios in which all pods can get restarted at the same time?

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/cass-operator#464]
**What happened?**
I had a cluster and wanted to change the storage class for new nodes that would be added when scaling up. This isn't possible since StatefulSets don't allow you to change the PVC template after it has been created. I circumvented this by doing the following:

* Scaled cass-operator deployment down to zero
* Deleted statefulsets with `--cascade=orphan`
* Updated my CassandraDatacenter spec with the new storage class  
* Scale up cass-operator

It may be worth noting that my CassandraDatacenter change was applied through a custom Helm chart which also scaled up cass-operator.

When cass-operator reconciled the CassandraDatacenter, it recreated the statefulsets. All of the Cassandra pods appeared to get recreated around the same time. This resulted in some data loss that I would obviously want to avoid in the future should I need to perform similar maintenance operations. The behavior has not been observed consistently.

With respect to data loss, I am unclear at this point how it happened since cass-operator configures the Cassandra pod with a prestop lifecycle hook that should run a drain.

cass-operator creates statefulsets with `podManagementPolicy: Parallel` which I thought might make it possible for pods to get deleted at the same time versus in a rolling fashion. Here is what the Kubernetes [docs](https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#pod-management-policy) say about Pod Management Policy:

> `Parallel` pod management tells the StatefulSet controller to launch or terminate all Pods in parallel, and not to wait for Pods to become Running and Ready or completely terminated prior to launching or terminating another Pod. This option only affects the behavior for scaling operations. Updates are not affected.

I also understand that cass-operator creates a PodDisruptionBudget for each CassandraDatacenter whose name is of the form <cassdc-name>-pdb. The PDB only allows for a single pod to be deleted at a time. There are times where a PDB cannot or isn't enforced. This must have been one of them.

**Did you expect to see something different?**
If it is in fact possible for all pods to get restarted at the same time like with the scenario I described, then I would like to avoid it in order to prevent possible data loss.

If the problem stems from all of the statefulsets getting recreated at the same time, then maybe we could consider introducing a flag to let cass-operator know it should recreate the statefulsets serially such that after it creates a statefulset cass-operator waits until the pods get recreated and come back up before moving onto the next statefulset. Note that I am mostly referring to `CheckRackCreation` method of `ReconciliationContext.

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Cass Operator version:

    `v1.10.4`
    
    

* Kubernetes version information:

    `kubectl version`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* Cass Operator Logs:

```
insert Cass Operator logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by burmanm** [comment]
Small note, this process isn't even possible in the default installation, as this is prevented by the admissionWebhook settings (if cass-operator is scaled down, then webhooks can't be called and the CassandraDatacenter can't be updated):

```
➜  testdata git:(master) ✗ kubectl edit cassdc dc2
error: cassandradatacenters.cassandra.datastax.com "dc2" could not be patched: Internal error occurred: failed calling webhook "vcassandradatacenter.kb.io": failed to call webhook: Post "https://cass-operator-webhook-service.cass-operator.svc:443/validate-cassandra-datastax-com-v1beta1-cassandradatacenter?timeout=10s": dial tcp 10.96.60.253:443: connect: connection refused
You can run `kubectl replace -f /tmp/kubectl-edit-2860280588.yaml` to try this update again.
➜  testdata git:(master) ✗
```

**Comment by burmanm** [comment]
Of course, one can remove the webhook and then try. That's what I did and then modified the StorageClass on the CassandraDatacenter object. And scaled back cass-operator, end result is that I can't even get a rolling restart to happen. I also added a new node to demonstrate it comes up with a different StorageClass:

```
➜  testdata git:(master) ✗ kubectl get all
NAME                                                    READY   STATUS    RESTARTS   AGE
pod/cass-operator-controller-manager-5c44d8f784-mk5n8   1/1     Running   0          8m48s
pod/cluster2-dc2-r1-sts-0                               2/2     Running   0          28m
pod/cluster2-dc2-r1-sts-1                               2/2     Running   0          28m
pod/cluster2-dc2-r1-sts-2                               2/2     Running   0          28m
pod/cluster2-dc2-r1-sts-3                               2/2     Running   0          28m
pod/cluster2-dc2-r1-sts-4                               2/2     Running   0          28m
pod/cluster2-dc2-r1-sts-5                               2/2     Running   0          2m21s

NAME                                           TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)                                        AGE
service/cass-operator-webhook-service          ClusterIP   10.96.60.253   <none>        443/TCP                                        47m
service/cluster2-dc2-additional-seed-service   ClusterIP   None           <none>        <none>                                         28m
service/cluster2-dc2-all-pods-service          ClusterIP   None           <none>        9042/TCP,8080/TCP,9103/TCP                     28m
service/cluster2-dc2-service                   ClusterIP   None           <none>        9042/TCP,9142/TCP,8080/TCP,9103/TCP,9160/TCP   28m
service/cluster2-seed-service                  ClusterIP   None           <none>        <none>                                         28m

NAME                                               READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/cass-operator-controller-manager   1/1     1            1           47m

NAME                                                          DESIRED   CURRENT   READY   AGE
replicaset.apps/cass-operator-controller-manager-5c44d8f784   1         1         1       47m

NAME                                   READY   AGE
statefulset.apps/cluster2-dc2-r1-sts   6/6     8m31s
➜  testdata git:(master) ✗ kubectl get pvc
NAME                                STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
server-data-cluster2-dc2-r1-sts-0   Bound    pvc-6e3f590a-d408-49d0-bd30-6a52281ed351   1Gi        RWO            standard          29m
server-data-cluster2-dc2-r1-sts-1   Bound    pvc-ffcb4cfd-ac34-4670-8747-9aa785efcd3a   1Gi        RWO            standard          29m
server-data-cluster2-dc2-r1-sts-2   Bound    pvc-97f73558-3375-442e-bb96-450f482af67f   1Gi        RWO            standard          29m
server-data-cluster2-dc2-r1-sts-3   Bound    pvc-ed3a55af-66a6-476a-90ff-082dfa332765   1Gi        RWO            standard          29m
server-data-cluster2-dc2-r1-sts-4   Bound    pvc-629a781f-1cd1-444d-b013-82e9fea846de   1Gi        RWO            standard          29m
server-data-cluster2-dc2-r1-sts-5   Bound    pvc-38a3efe3-efe5-4b51-8c85-7bd0e683d900   1Gi        RWO            standard-retain   3m12s
➜  testdata git:(master) ✗
```

**Comment by burmanm** [comment]
The only way I could get them all to terminate at once (and restart at once) is by omitting the ``--cascade=orphan`` 

And even in that case, I see drain being called:

```
INFO  [nioEventLoopGroup-2-1] 2022-12-20 11:58:58,325 Cli.java:617 - address=/0:0:0:0:0:0:0:1:47696 url=/api/v0/ops/node/drain status=200 OK
```

**Comment by burmanm** [comment]
> cass-operator creates statefulsets with podManagementPolicy: Parallel which I thought might make it possible for pods to get deleted at the same time versus in a rolling fashion.

This has no impact, but setting it to ``OrderedReady`` would slow down scaling a new cluster (since there would be no new pods with management-api started).

> If the problem stems from all of the statefulsets getting recreated at the same time, then maybe we could consider introducing a flag to let cass-operator know it should recreate the statefulsets serially such that after it creates a statefulset cass-operator waits until the pods get recreated and come back up before moving onto the next statefulset

This isn't the problem and would not help. Also, changing that behavior would break balanced racks, with cass-operator first starting all the nodes in a single rack until moving to next ones. That causes its own issues with seed placements. Definitely not something we want as the default.

**Comment by jsanda** [comment]
@burmanm I found out yesterday that the cluster where this happened was running cass-operator v1.4.0. I previously assumed it was running v1.10.x. Can you test again with v1.4.0 and Kubernetes 1.17?

**Comment by burmanm** [comment]
Why would we spend time investigating 1.4.0? If it has a bug or not won't matter to anything. That said, I don't think 1.4.0 has drain prestop autoconfigured, that's supposed to be done by whoever deploys the CassDc yaml.

**Comment by jsanda** [comment]
As you pointed out the drain prestop was added in 1.5.0. I can close this. Thanks for investigating.
