### ISSUE TITLE
Replace default images for DSE

### ISSUE THREAD

**Issue by burmanm** [k8ssandra/cass-operator#479]
**What is missing?**
We currently set the default DSE images from repository `datastax/dse-server`. To allow new features to work with the DSE, we need to change this repository in the future to be `datastax/dse-mgmtapi-6_8` with the OSS mgmt-api included.

The cutting point will be >= 6.8.31. Older releases will use older repo, newer will use new one. To do this, we will parse the serverVersion in the image.go and check if the `imageConfig` was loaded with defaults (if not - we will not override anything). And in the case of defaults, we will use the correct repository depending on the version. 

**Why do we need it?**
For MCAC replacement, CDC, async endpoints, etc. And to make it easier to support single mgmt-api target.

**Environment**

* Cass Operator version:

    `Insert image tag or Git SHA here`
    
    

**Anything else we need to know?**:

**Comment by Miles-Garnsey** [comment]
@emerkle826  has gone ahead and published images down to 6.8.25 I believe, is there any reason we can't cut at that version?

There will be users who would like CDC and other new features to work at lower versions without forcing an upgrade I imagine...

Generally I don't have a problem with this proposal, but I think if we ever release a cass-operator v2 we need to pay close attention to partitioning the API fields more carefully to avoid situations like this, where two fields (e.g. image coordinates and serverVersion, serverType etc.) can be in conflict.

**Comment by burmanm** [comment]
DSE doesn't traditionally add new features to older versions, so upgrade time it is. But yes, there's a reason, the existing 6.8.25 (etc) are deployed with the old image already. 6.8.31 is more likely to be a version that's not deployed by anyone at this point (or very small amount). If we waited CDC support to land to current official images, then 6.8.32 would be the earliest one.

Why is serverVersion/serverType in conflict here? I don't understand the comment.

**Comment by Miles-Garnsey** [comment]
> Why is serverVersion/serverType in conflict here? I don't understand the comment.

Because e.g. serverVersion doesn't actually control the version, that's a feature of the image and not under control of the operator whenever the image is specified.

**Comment by burmanm** [comment]
Are you suggesting we prevent users from overriding the image?

**Comment by Miles-Garnsey** [comment]
No I'm suggesting we remove the serverType/serverVersion fields. Both can be provided by a management API initContainer if the operator needs to know them...
