### ISSUE TITLE
Replace cass-config-builder with Go

### ISSUE THREAD

**Issue by burmanm** [k8ssandra/cass-operator#512]
### What is missing?

We currently run cass-config-builder, which is not compatible with the new configs in 4.1 and up. The steps that we will need to implement are created as subtickets (we don't need to replicate entire cass-config-builder as a lot of it isn't Kubernetes related).

- [x] #513 
- [x] #514

In addition, some smaller ones:

- [ ] Sanitize env variables (including cassandra-env.sh additionals) to prevent any injections
- [ ] Get rid of some env variables that are not relevant to Kubernetes installations
- [ ] Add ability to set Cassandra version to 5.x.x also
- [ ] Support DSE 6.8.x and OSS versions

### Why is this needed?

Refactoring cass-config-builder is time consuming, is built on language we don't use (Clojure) and it's a resource hog.

### Additional info

We need to decide which versions will use the newer builder. Do we want to keep the old one for the stuff where it has worked previously (3.11.x, 4.0.x and DSE 6.8.x) and only use it for the newer stuff - or do we want to replace and use a common path for all versions?

Restricting it to newer ones would reduce the amount of boilerplate and different paths, but of course would require different deployment model for different versions.

**Comment by burmanm** [comment]
A small note to overall approach. We need the base config in many cases, but that's not available elsewhere than the image itself. So perhaps initcontainer is still necessary (or sane approach).

**Comment by burmanm** [comment]
Reopening until cass-operator part is merged also.

**Comment by c3-clement** [comment]
hello @burmanm 

Is it still possible to use cass-config-builder over k8ssandra-client for cassandra 4.1 ?

> We currently run cass-config-builder, which is not compatible with the new configs in 4.1 and up

Do you know where I can find documentation about cass-config-builder and Cassandra 4.1 compatibility?

Thanks!

**Comment by burmanm** [comment]
You need to override two init containers if you wish to use the older one, we automatically deploy k8ssandra-client for 4.1 installations.

cass-config-builder has no support for 4.1 and is not tested with it. It would deploy 4.0.0 config as the base template for 4.1. Why would you want to use the old cass-config-builder instead?

**Comment by c3-clement** [comment]
> You need to override two init containers if you wish to use the older one, we automatically deploy k8ssandra-client for 4.1 installations.
> 
> cass-config-builder has no support for 4.1 and is not tested with it. It would deploy 4.0.0 config as the base template for 4.1. Why would you want to use the old cass-config-builder instead?

Thank you for your answer!

> Why would you want to use the old cass-config-builder instead?

That's a long story. To make it short, we have to get the k8ssandra-client image approved by our customers security teams, while the cass-config-builder image is already approved

**Comment by burmanm** [comment]
> To make it short, we have to get the k8ssandra-client image approved by our customers security teams, while the cass-config-builder image is already approved

Right. Well, it might make sense to get that process done as our active work revolves around k8ssandra-client for config building. That includes 5.0 support also.
