### ISSUE TITLE
Tests are missing proper mock checks

### ISSUE THREAD

**Issue by burmanm** [k8ssandra/cass-operator#526]
### What is missing?

A lot of tests have mocks used, but their assertions are never called - thus not verifying if the calls were actually made or not. This makes a lot of tests a bit questionable if they're actually testing what they're supposed to.

### Why is this needed?

Tests should be trusted to verify that they test what they claim to test.

**Comment by olim7t** [comment]
This sounds like a good refactoring task, I've added the label and am moving this to the backlog.
