### ISSUE TITLE
Cassandra pods are failing to provision due to "Back-off restarting failed container"

### ISSUE THREAD

**Issue by Priyaranimishra** [k8ssandra/cass-operator#529]
### What happened?

I am using cass-operator to deploy cassandra nodes. I am able to successfully installed the cass-operator on openshift cluster. 

I am seeing error  "Back-off restarting failed container" while creating CassandraDatacenters.

```
oc logs pod/development-dc1-rack2-sts-0 server-system-logger
tail: cannot open '/var/log/cassandra/system.log' for reading: No such file or directory
oc logs pod/development-dc1-rack2-sts-0 cassandra
Starting Management API
/docker-entrypoint.sh: line 97: /opt/metrics-collector/config/metric-collector.yaml: Permission denied

```
I have set dockerImageRunsAsCassandra: false in the CassandraDatacenter spec.

Could you please assist us?

Thanks

### What did you expect to happen?

All CassandraDataCenter Pods should be  running successfully.

### How can we reproduce it (as minimally and precisely as possible)?

Could you please reply as soon as possible?

### cass-operator version

cass-operator.v1.14.0

### Kubernetes version

Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:33:11Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"darwin/amd64"} Kustomize Version: v4.5.7 Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.17+71d09da", GitCommit:"7c1c7c93b1fa3a7ebd0bd68e461977c696c7968e", GitTreeState:"clean", BuildDate:"2023-03-24T17:36:51Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}

**Comment by burmanm** [comment]
> I have set dockerImageRunsAsCassandra: false in the CassandraDatacenter spec.

Why?

**Comment by Priyaranimishra** [comment]
I have found on some docs that need to set dockerImageRunsAsCassandra: false ...Even though I have tried without adding this parameter, it is failing @burmanm

**Comment by Miles-Garnsey** [comment]
Hi @Priyaranimishra, can you please provide the full manifests you're deploying and the status, of the k8s resources including events for the pods and statefulsets.

**Comment by burmanm** [comment]
Given that this targets an old version, I'm closing this. If this issue persists with 1.17.2, please attach the CassandraDatacenter that was deployed.
