### ISSUE TITLE
Point images coordinates to pull from cr.dtsx.io and cr.k8ssandra.io

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/cass-operator#560]
We need to modify the image coordinates that we're pulling to use `cr.dtsx.io/datastax` and `cr.k8ssandra.io/k8ssandra`. This will allow use to abstract away from the backend registry that we're currently relying on and allow us to switch without making any changes to the code nor requiring an upgrade.
This will also allow us to gather usage analytics to better understand how the different images and components get pulled.

**Comment by burmanm** [comment]
This is actually done.
