### ISSUE TITLE
Read Timeout Issue

### ISSUE THREAD

**Issue by shengzhizhou** [k8ssandra/cass-operator#569]
Hi, 
I had a timeout issue when I run simply "select count(*)" using CqlConnection from C# .Net6 application, the table is too big to read. I have increase the read_request_timeout_in_ms to 30000 (30secs) but still has issue. FYI The Cassandra and c# application are setup in Kubernetes cluster.
What's the best practice to handle this case? I heard DataStax Bulk Loader tool can be very efficient, is it a good practice to embed that tool into a .net6 application in a Linux image?
Thanks.

**Comment by burmanm** [comment]
Closing this as it wasn't directly related to cass-operator (and could be stale).
