### ISSUE TITLE
Add a GC CassandraTask which can target specific nodes or a full DC

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/cass-operator#580]
We'd need to have support for [garbagecollect](https://cassandra.apache.org/doc/latest/cassandra/tools/nodetool/garbagecollect.html) as CassandraTask job type.

This Cassandra task should support the granularity and jobs arguments.

```[tasklist]
### Definition of Done
- [ ] A new CassandraTask job type is added to support garbagecollect, with support for the granularity and jobs arguments
```

**Comment by burmanm** [comment]
Nit, this should follow the template in this repository.

**Comment by adejanovski** [comment]
> Nit, this should follow the template in this repository.

ok, I'll make sure to comply next time 👍
