### ISSUE TITLE
Enable tsreload from cass-operator

### ISSUE THREAD

**Issue by Miles-Garnsey** [k8ssandra/cass-operator#651]
### What is missing?
Management API will [soon](https://github.com/k8ssandra/management-api-for-apache-cassandra/issues/483) add a new endpoint which forces a reload of the truststore. This is to enable new CA certs to be added to the node without a full restart.

I'm not sure what the best way to access this functionality is, but I presume it should probably be called from cass-operator, since that is where logic to manage the nodes usually resides. 

I can see two options:

1. We add an annotation to the pod (similar to the restart annotations that we normally add) and cass-operator picks this up before calling the management API endpoint on the specific node that needs a reload. 
1. We create a new CassandraTask which does the same.

burmanm what are your thoughts on this? Any preference?

### Why is this needed?
We have CA reloading problems.

┆Issue is synchronized with this [Jira Story](https://datastax.jira.com/browse/CASS-7) by [Unito](https://www.unito.io)
┆Reviewer: Michael Burman
┆Fix Versions: 2024-10
┆Issue Number: CASS-7

**Comment by burmanm** [comment]
client.go change + a task is fine (I'm not a fan of pod annotations, since we don't listen to those). I'm assuming this is a DSE specific feature.

**Comment by Miles-Garnsey** [comment]
> client.go change + a task is fine (I'm not a fan of pod annotations, since we don't listen to those). I'm assuming this is a DSE specific feature.

Roger. It is DSE only, yes. We don't need to worry about this in OSS Cassandra.
