### ISSUE TITLE
cass-operator may crash if storageClassName is not set

### ISSUE THREAD

**Issue by c3-clement** [k8ssandra/cass-operator#687]
### What happened?

If `Spec.StorageConfig.CassandraDataVolumeClaimSpec.StorageClassName` is not set on the datacenter CR, `StorageClassName` will be a null pointer.
`StorageClassName` is getting dereferenced here https://github.com/k8ssandra/cass-operator/blame/master/pkg/reconciliation/reconcile_datacenter.go#L191 without a null check before.

If storageClassName is null, the operator will segfault.

### What did you expect to happen?

I expect cass-operator to handle the case when `storageClassName` is not set by the user.
The operator should try to fetch the `default` storage class instead and call `storageClass()` with the name of the default storage class.

### How can we reproduce it (as minimally and precisely as possible)?

I observed the issue when testing restoration.
I believe the issue will happen when storage expansion is triggered and when storage class name is not set.

I'm not sure why storage expansion got triggered during restoration.

### cass-operator version

1.22

### Kubernetes version

1.29

### Method of installation

helm

**Comment by burmanm** [comment]
Ah, PersistentVolume has type string and for PersistentVolumeClaimSpec they made it *string.

**Comment by burmanm** [comment]
Related: https://github.com/k8ssandra/cass-operator/issues/123
