### ISSUE TITLE
Add read only root FS support for more server types

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/cass-operator#701]
The readOnlyRootFilesystem feature relies on using the new config builder from k8ssandra-client, which hasn't been enabled for server type/version other than Cassandra 4.1+.
We'd need to enable the new config builder on additional server types and images if the readOnlyRootFilesystem is set to true and see if there are impacts.

This should only be possible for new installations and we should not allow a change in value, which would modify the configuration files due to different defaults.

┆Issue is synchronized with this [Jira Story](https://datastax.jira.com/browse/CASS-64) by [Unito](https://www.unito.io)
┆Fix Versions: 2024-10
┆Issue Number: CASS-64

**Comment by burmanm** [comment]
Changes to original spec. We do not enforce k8ssandra-client if you pick up readOnlyRootFilesystem, but instead allow using that feature even if the k8ssandra-client is not used.

And then we add the missing parts for DSE to work with it (if using mgmt-api v0.1.86 or newer). Cassandra 3.11 and 4.0 will not function with this functionality after this ticket, only HCD, DSE and Cassandra 4.1 and newer are supported.
