### ISSUE TITLE
default image coordinates cannot be overridden in the helm chart

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/cass-operator#715]
The image config contains default coordinates for each server type, which define where the corresponding images will get pulled from (see [here](https://github.com/k8ssandra/cass-operator/blob/master/config/manager/image_config.yaml#L17-L27)).

These defaults are [hardcoded in the helm template](https://github.com/k8ssandra/k8ssandra/blob/main/charts/cass-operator/templates/configmap.yaml#L55-L65) for the image config, making them impossible to customize.

We need these overrides to be possible so we can use them for private registry setups.

┆Issue is synchronized with this [Jira Story](https://datastax.jira.com/browse/CASS-70) by [Unito](https://www.unito.io)
┆Fix Versions: 2024-10
┆Issue Number: CASS-70

**Comment by apa64** [comment]
Was the default changed from docker.io to dtsx.io? The operator fails now in a disconnected environment where there's a mirror registry only for docker.io images.

**Comment by adejanovski** [comment]
Yes, we now use a proxy for the image pulls as default.
You can override the registry at installation time and have the various images pulled from wherever you want. This is similar to how you would configure cass-operator to use a private registry.

**Comment by apa64** [comment]
> You can override the registry at installation time

Can I configure this in a Subscription object? Can I set only the registry for both cass-operator and Cassandra images, not the whole path?

Something like this?

```yaml
kind: Subscription
spec:
  ...
  config:
    someImage: myreg.local/...
```
