### ISSUE TITLE
Concurrent restarts of previously bootstrapped nodes should be the default

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/cass-operator#731]
### What is missing?
We've recently introduced the ability to allow concurrent startup of previously bootstrapped nodes as a feature flag.
This prevents cluster downtime in case one pods fails to restart (because of corrupt sstables for example) and blocks other pods from restarting if they need to.

We'd need to make this the default now and remove the annotation that was used as a feature flag.

### Why is this needed?
This feature protects the availability of clusters in case of incidents.

┆Issue is synchronized with this [Jira Story](https://datastax.jira.com/browse/CASS-79) by [Unito](https://www.unito.io)
┆Reviewer: Miles Garnsey
┆Fix Versions: 2024-12
┆Issue Number: CASS-79

**Comment by burmanm** [comment]
> We'd need to make this the default now and remove the annotation that was used as a feature flag.

I think we should keep the feature flag to allow disabling this behavior, just change evaluation to check for false instead of true.

**Comment by adejanovski** [comment]
I'm ok with that 👍
