### ISSUE TITLE
K8SSAND-168 ⁃ Updating the podTemplateSpec while dc is shutdown will trigger an additional restart of C* pods

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/cass-operator#9]
While testing backup-restore with medusa-operator I noticed an additional restart of C* pods that further delayed the restore process. 

Here is a brief summary of the steps involved:

1. Update CassandraDatacenter by setting `stopped: true`
1. Wait for StatefulSet to scale down to zero
1. Update the `podTemplateSpec` by adding some environment variables to the `medusa-restore` initContainer
  * Note that any change to the `podTemplateSpec` should be sufficient to trigger to reproduce this
1. Set `stopped: false`

The StatefulSet (or StatefulSets) will scale back up to the prior number of replicas. After the Cassandra pods become ready, cass-operator applies the changes in step 3 to the StatefulSet. This in turn causes a StatefulSet update which is in effect a cluster-wide rolling restart.

Certainly in the context of backup/restore we want to avoid that additional StatefulSet update. jimdickinson do you know if there are any scenarios in which we would want that delayed update?

┆Issue is synchronized with this [Jira Bug](https://k8ssandra.atlassian.net/browse/K8SSAND-168) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-168
┆priority: Medium

**Comment by jdonenine** [comment]
Should step 4

> 4. Set `stopped: true`

be Set `stopped: false`?

**Comment by jsanda** [comment]
@jdonenine yes thanks for catching that!

**Comment by bradfordcp** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/K8ssandra-Grooming-623b197f1fcd4800110540ef/issues/k8ssandra/cass-operator/9?planning-poker) with ZenHub @burmanm @jsanda

**Comment by jsanda** [comment]
Closing as won't fixed. If there is still an issue here, should be opened in k8ssandra-operator.

**Comment by bradfordcp** [comment]
So is / was this an issue with case-operator?

**Comment by jsanda** [comment]
Yes, this is due to behavior in cass-operator.
